// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iw4cFYZtgxW7YvDehgMC47
// Component: StWVtS8o04o
import * as React from "react";
import Head from "next/head";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_project_web.module.css"; // plasmic-import: iw4cFYZtgxW7YvDehgMC47/projectcss
import * as sty from "./PlasmicPeoplePage.module.css"; // plasmic-import: StWVtS8o04o/css
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: RWzvUW32AX/icon
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: 4NZJoj-fIt/icon
import Line20Icon from "./icons/PlasmicIcon__Line20"; // plasmic-import: dJGJxsVm5vx/icon
import Line8Icon from "./icons/PlasmicIcon__Line8"; // plasmic-import: OWLbkpHPcZo/icon
import Polygon1Icon from "./icons/PlasmicIcon__Polygon1"; // plasmic-import: QaRBHQulwLs/icon
import Rectangle22Icon from "./icons/PlasmicIcon__Rectangle22"; // plasmic-import: Edq9j_F817L/icon
import Line21Icon from "./icons/PlasmicIcon__Line21"; // plasmic-import: Tx8VCqGnqiZ/icon
import Line22Icon from "./icons/PlasmicIcon__Line22"; // plasmic-import: 3w-a0WnCXsB/icon
import Arrow2Icon from "./icons/PlasmicIcon__Arrow2"; // plasmic-import: d9dK44K72X2/icon

export const PlasmicPeoplePage__VariantProps = new Array();

export const PlasmicPeoplePage__ArgProps = new Array();

function PlasmicPeoplePage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"peoplePageDesktop"}
            data-plasmic-override={overrides.peoplePageDesktop}
            className={classNames(defaultcss.all, sty.peoplePageDesktop)}
          >
            {false ? (
              <Line5Icon
                className={classNames(defaultcss.all, sty.svg___9Ooue)}
                role={"img"}
              />
            ) : null}

            <div
              data-plasmic-name={"photo202108171656131"}
              data-plasmic-override={overrides.photo202108171656131}
              className={classNames(defaultcss.all, sty.photo202108171656131)}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__stjDd)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__unom)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__dnDmz)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__jqFz)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__yj4B)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg___8M0BI)}
              role={"img"}
            />

            <Line20Icon
              className={classNames(defaultcss.all, sty.svg__qg2Ij)}
              role={"img"}
            />

            <Line8Icon
              className={classNames(defaultcss.all, sty.svg__f4628)}
              role={"img"}
            />

            <div
              data-plasmic-name={"group8"}
              data-plasmic-override={overrides.group8}
              className={classNames(defaultcss.all, sty.group8)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___0YSXj
                )}
              >
                {"О ПРОЕКТЕ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__aU1D4
                )}
              >
                {"ПОДДЕРЖАТЬ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__r8Juq
                )}
              >
                {"ЛЮДИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__rx0J7
                )}
              >
                {"НОВОСТИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__y20W
                )}
              >
                {"КАРТА ПРЕСТУПНИКОВ"}
              </div>
            </div>

            <div
              data-plasmic-name={"group21"}
              data-plasmic-override={overrides.group21}
              className={classNames(defaultcss.all, sty.group21)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__qdHgd
                )}
              >
                {"ПРЕСТУПНИКИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__bipEc
                )}
              >
                {"ПОСОБНИКИ"}
              </div>
            </div>

            <div
              data-plasmic-name={"group1"}
              data-plasmic-override={overrides.group1}
              className={classNames(defaultcss.all, sty.group1)}
            >
              <div
                data-plasmic-name={"verify1"}
                data-plasmic-override={overrides.verify1}
                className={classNames(defaultcss.all, sty.verify1)}
              />

              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(defaultcss.all, sty.rectangle3)}
              />
            </div>

            <div
              data-plasmic-name={"group10"}
              data-plasmic-override={overrides.group10}
              className={classNames(defaultcss.all, sty.group10)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__oElec
                )}
              >
                {"Выбрать регион"}
              </div>

              <Polygon1Icon
                className={classNames(defaultcss.all, sty.svg__izrp5)}
                role={"img"}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__eg5O
              )}
            >
              {"ЛЮДИ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__m2Qg6
              )}
            >
              {"НАШИ ПАРТНЕРЫ"}
            </div>

            <div
              data-plasmic-name={"profile"}
              data-plasmic-override={overrides.profile}
              className={classNames(defaultcss.all, sty.profile)}
            >
              <div
                data-plasmic-name={"group24"}
                data-plasmic-override={overrides.group24}
                className={classNames(defaultcss.all, sty.group24)}
              >
                <div
                  data-plasmic-name={"image27"}
                  data-plasmic-override={overrides.image27}
                  className={classNames(defaultcss.all, sty.image27)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg__cLm3R)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__neK5K
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__sCi73
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile2"}
              data-plasmic-override={overrides.profile2}
              className={classNames(defaultcss.all, sty.profile2)}
            >
              <div
                data-plasmic-name={"group25"}
                data-plasmic-override={overrides.group25}
                className={classNames(defaultcss.all, sty.group25)}
              >
                <div
                  data-plasmic-name={"image28"}
                  data-plasmic-override={overrides.image28}
                  className={classNames(defaultcss.all, sty.image28)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg___0Eq1U)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__tqVeR
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__mA55T
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile3"}
              data-plasmic-override={overrides.profile3}
              className={classNames(defaultcss.all, sty.profile3)}
            >
              <div
                data-plasmic-name={"group26"}
                data-plasmic-override={overrides.group26}
                className={classNames(defaultcss.all, sty.group26)}
              >
                <div
                  data-plasmic-name={"image29"}
                  data-plasmic-override={overrides.image29}
                  className={classNames(defaultcss.all, sty.image29)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg__baoVm)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__hYuYy
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__hfSkh
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile4"}
              data-plasmic-override={overrides.profile4}
              className={classNames(defaultcss.all, sty.profile4)}
            >
              <div
                data-plasmic-name={"group27"}
                data-plasmic-override={overrides.group27}
                className={classNames(defaultcss.all, sty.group27)}
              >
                <div
                  data-plasmic-name={"image30"}
                  data-plasmic-override={overrides.image30}
                  className={classNames(defaultcss.all, sty.image30)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg__v05Sj)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__f35Wc
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__wbRSa
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile5"}
              data-plasmic-override={overrides.profile5}
              className={classNames(defaultcss.all, sty.profile5)}
            >
              <div
                data-plasmic-name={"group28"}
                data-plasmic-override={overrides.group28}
                className={classNames(defaultcss.all, sty.group28)}
              >
                <div
                  data-plasmic-name={"image31"}
                  data-plasmic-override={overrides.image31}
                  className={classNames(defaultcss.all, sty.image31)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg__vjSul)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__kko4O
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__t8V29
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile6"}
              data-plasmic-override={overrides.profile6}
              className={classNames(defaultcss.all, sty.profile6)}
            >
              <div
                data-plasmic-name={"group29"}
                data-plasmic-override={overrides.group29}
                className={classNames(defaultcss.all, sty.group29)}
              >
                <div
                  data-plasmic-name={"image32"}
                  data-plasmic-override={overrides.image32}
                  className={classNames(defaultcss.all, sty.image32)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg__bhK94)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__lz4AT
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__diWEl
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile7"}
              data-plasmic-override={overrides.profile7}
              className={classNames(defaultcss.all, sty.profile7)}
            >
              <div
                data-plasmic-name={"group30"}
                data-plasmic-override={overrides.group30}
                className={classNames(defaultcss.all, sty.group30)}
              >
                <div
                  data-plasmic-name={"image33"}
                  data-plasmic-override={overrides.image33}
                  className={classNames(defaultcss.all, sty.image33)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg__dLbFv)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___8HBz
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__mZHQ
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile8"}
              data-plasmic-override={overrides.profile8}
              className={classNames(defaultcss.all, sty.profile8)}
            >
              <div
                data-plasmic-name={"group31"}
                data-plasmic-override={overrides.group31}
                className={classNames(defaultcss.all, sty.group31)}
              >
                <div
                  data-plasmic-name={"image34"}
                  data-plasmic-override={overrides.image34}
                  className={classNames(defaultcss.all, sty.image34)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg__gLs3)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__acUD
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__hOghF
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile9"}
              data-plasmic-override={overrides.profile9}
              className={classNames(defaultcss.all, sty.profile9)}
            >
              <div
                data-plasmic-name={"group32"}
                data-plasmic-override={overrides.group32}
                className={classNames(defaultcss.all, sty.group32)}
              >
                <div
                  data-plasmic-name={"image35"}
                  data-plasmic-override={overrides.image35}
                  className={classNames(defaultcss.all, sty.image35)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg__aoz8D)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___2Hn4S
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__nciGp
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile10"}
              data-plasmic-override={overrides.profile10}
              className={classNames(defaultcss.all, sty.profile10)}
            >
              <div
                data-plasmic-name={"group33"}
                data-plasmic-override={overrides.group33}
                className={classNames(defaultcss.all, sty.group33)}
              >
                <div
                  data-plasmic-name={"image36"}
                  data-plasmic-override={overrides.image36}
                  className={classNames(defaultcss.all, sty.image36)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg__hpZk5)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__d4HcB
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__mtEw0
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile11"}
              data-plasmic-override={overrides.profile11}
              className={classNames(defaultcss.all, sty.profile11)}
            >
              <div
                data-plasmic-name={"group34"}
                data-plasmic-override={overrides.group34}
                className={classNames(defaultcss.all, sty.group34)}
              >
                <div
                  data-plasmic-name={"image37"}
                  data-plasmic-override={overrides.image37}
                  className={classNames(defaultcss.all, sty.image37)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg___7MfVh)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__yPIw
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__kLkmV
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile12"}
              data-plasmic-override={overrides.profile12}
              className={classNames(defaultcss.all, sty.profile12)}
            >
              <div
                data-plasmic-name={"group35"}
                data-plasmic-override={overrides.group35}
                className={classNames(defaultcss.all, sty.group35)}
              >
                <div
                  data-plasmic-name={"image38"}
                  data-plasmic-override={overrides.image38}
                  className={classNames(defaultcss.all, sty.image38)}
                />
              </div>

              <Rectangle22Icon
                className={classNames(defaultcss.all, sty.svg___6MiNp)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__im58D
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___3JL0
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__z0Ke
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/ видео подтверждения и тра-тра-та наш бот @botbotbot"
              }
            </div>

            <div
              data-plasmic-name={"union1"}
              data-plasmic-override={overrides.union1}
              className={classNames(defaultcss.all, sty.union1)}
            />

            <div
              data-plasmic-name={"union8"}
              data-plasmic-override={overrides.union8}
              className={classNames(defaultcss.all, sty.union8)}
            />

            <div
              data-plasmic-name={"union3"}
              data-plasmic-override={overrides.union3}
              className={classNames(defaultcss.all, sty.union3)}
            />

            <div
              data-plasmic-name={"union9"}
              data-plasmic-override={overrides.union9}
              className={classNames(defaultcss.all, sty.union9)}
            />

            <div
              data-plasmic-name={"union5"}
              data-plasmic-override={overrides.union5}
              className={classNames(defaultcss.all, sty.union5)}
            />

            <div
              data-plasmic-name={"union10"}
              data-plasmic-override={overrides.union10}
              className={classNames(defaultcss.all, sty.union10)}
            />

            <div
              data-plasmic-name={"union2"}
              data-plasmic-override={overrides.union2}
              className={classNames(defaultcss.all, sty.union2)}
            />

            <div
              data-plasmic-name={"union11"}
              data-plasmic-override={overrides.union11}
              className={classNames(defaultcss.all, sty.union11)}
            />

            <div
              data-plasmic-name={"union4"}
              data-plasmic-override={overrides.union4}
              className={classNames(defaultcss.all, sty.union4)}
            />

            <div
              data-plasmic-name={"union12"}
              data-plasmic-override={overrides.union12}
              className={classNames(defaultcss.all, sty.union12)}
            />

            <div
              data-plasmic-name={"union6"}
              data-plasmic-override={overrides.union6}
              className={classNames(defaultcss.all, sty.union6)}
            />

            <div
              data-plasmic-name={"union13"}
              data-plasmic-override={overrides.union13}
              className={classNames(defaultcss.all, sty.union13)}
            />

            <div
              data-plasmic-name={"union7"}
              data-plasmic-override={overrides.union7}
              className={classNames(defaultcss.all, sty.union7)}
            />

            <div
              data-plasmic-name={"union14"}
              data-plasmic-override={overrides.union14}
              className={classNames(defaultcss.all, sty.union14)}
            />

            <div
              data-plasmic-name={"rectangle21"}
              data-plasmic-override={overrides.rectangle21}
              className={classNames(defaultcss.all, sty.rectangle21)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__sUMgg
              )}
            >
              {
                "Публикуемые личные данные получены из открытых источников методом социальной инженерии или же непосредственно от читателей. Данные публикуются исключительно с целью упрощения последующего расследования преступлений. \n\nКоманда чкб не призывает к насилию. выступает против любого вида дискриминации и порицает разжигание социальной вражды."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__aimWe
              )}
            >
              {"Связаться с нами через бота"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__gGaxi
              )}
            >
              {"Ошибка в тексте?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__lPkJg
              )}
            >
              {"ЧЕРНАЯ КНИГА БЕЛАРУСИ"}
            </div>

            <div
              data-plasmic-name={"group20"}
              data-plasmic-override={overrides.group20}
              className={classNames(defaultcss.all, sty.group20)}
            >
              <div
                data-plasmic-name={"rectangle18"}
                data-plasmic-override={overrides.rectangle18}
                className={classNames(defaultcss.all, sty.rectangle18)}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__ncp6Q
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/"
              }
            </div>

            <Line21Icon
              className={classNames(defaultcss.all, sty.svg__yBnFo)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__nfZv
              )}
            >
              {"Милиционер"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__y2M2Y
              )}
            >
              {"ОМОН"}
            </div>

            <div
              data-plasmic-name={"губопик"}
              data-plasmic-override={overrides.губопик}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.губопик
              )}
            >
              {"ГУБОПиК\r"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__tAlvy
              )}
            >
              {"КГБ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__p3K7S
              )}
            >
              {"Внутренние Войска"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__pAdXg
              )}
            >
              {"ГАИ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__w9CzZ
              )}
            >
              {"Вооруженные Силы"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__x9Ow4
              )}
            >
              {"ДИН (Департамент Исполнения Наказаний)"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__i48Oa
              )}
            >
              {"Следственный комитет"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__es4XP
              )}
            >
              {"Прокурор"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__xyTIp
              )}
            >
              {"Судья"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__jgQy
              )}
            >
              {"Погран. комитет"}
            </div>

            <Line22Icon
              className={classNames(defaultcss.all, sty.svg__bFadI)}
              role={"img"}
            />

            <Line22Icon
              className={classNames(defaultcss.all, sty.svg__pDsfX)}
              role={"img"}
            />

            <Line22Icon
              className={classNames(defaultcss.all, sty.svg__flLkw)}
              role={"img"}
            />

            <Line22Icon
              className={classNames(defaultcss.all, sty.svg__que4L)}
              role={"img"}
            />

            <Line22Icon
              className={classNames(defaultcss.all, sty.svg__rwic5)}
              role={"img"}
            />

            <Line22Icon
              className={classNames(defaultcss.all, sty.svg__c8Jp6)}
              role={"img"}
            />

            <Line22Icon
              className={classNames(defaultcss.all, sty.svg__dc2A)}
              role={"img"}
            />

            <Line22Icon
              className={classNames(defaultcss.all, sty.svg__tde6X)}
              role={"img"}
            />

            <Line22Icon
              className={classNames(defaultcss.all, sty.svg__k9Bgb)}
              role={"img"}
            />

            <Line22Icon
              className={classNames(defaultcss.all, sty.svg__ylWCd)}
              role={"img"}
            />

            <div
              data-plasmic-name={"group36"}
              data-plasmic-override={overrides.group36}
              className={classNames(defaultcss.all, sty.group36)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__o3AFo
                )}
              >
                {"Показать больше"}
              </div>

              <Arrow2Icon
                className={classNames(defaultcss.all, sty.svg__v0FGo)}
                role={"img"}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "peoplePageDesktop",
    "photo202108171656131",
    "group8",
    "group21",
    "group1",
    "verify1",
    "rectangle3",
    "group10",
    "profile",
    "group24",
    "image27",
    "profile2",
    "group25",
    "image28",
    "profile3",
    "group26",
    "image29",
    "profile4",
    "group27",
    "image30",
    "profile5",
    "group28",
    "image31",
    "profile6",
    "group29",
    "image32",
    "profile7",
    "group30",
    "image33",
    "profile8",
    "group31",
    "image34",
    "profile9",
    "group32",
    "image35",
    "profile10",
    "group33",
    "image36",
    "profile11",
    "group34",
    "image37",
    "profile12",
    "group35",
    "image38",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18",
    "губопик",
    "group36"
  ],

  peoplePageDesktop: [
    "peoplePageDesktop",
    "photo202108171656131",
    "group8",
    "group21",
    "group1",
    "verify1",
    "rectangle3",
    "group10",
    "profile",
    "group24",
    "image27",
    "profile2",
    "group25",
    "image28",
    "profile3",
    "group26",
    "image29",
    "profile4",
    "group27",
    "image30",
    "profile5",
    "group28",
    "image31",
    "profile6",
    "group29",
    "image32",
    "profile7",
    "group30",
    "image33",
    "profile8",
    "group31",
    "image34",
    "profile9",
    "group32",
    "image35",
    "profile10",
    "group33",
    "image36",
    "profile11",
    "group34",
    "image37",
    "profile12",
    "group35",
    "image38",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18",
    "губопик",
    "group36"
  ],

  photo202108171656131: ["photo202108171656131"],
  group8: ["group8"],
  group21: ["group21"],
  group1: ["group1", "verify1", "rectangle3"],
  verify1: ["verify1"],
  rectangle3: ["rectangle3"],
  group10: ["group10"],
  profile: ["profile", "group24", "image27"],
  group24: ["group24", "image27"],
  image27: ["image27"],
  profile2: ["profile2", "group25", "image28"],
  group25: ["group25", "image28"],
  image28: ["image28"],
  profile3: ["profile3", "group26", "image29"],
  group26: ["group26", "image29"],
  image29: ["image29"],
  profile4: ["profile4", "group27", "image30"],
  group27: ["group27", "image30"],
  image30: ["image30"],
  profile5: ["profile5", "group28", "image31"],
  group28: ["group28", "image31"],
  image31: ["image31"],
  profile6: ["profile6", "group29", "image32"],
  group29: ["group29", "image32"],
  image32: ["image32"],
  profile7: ["profile7", "group30", "image33"],
  group30: ["group30", "image33"],
  image33: ["image33"],
  profile8: ["profile8", "group31", "image34"],
  group31: ["group31", "image34"],
  image34: ["image34"],
  profile9: ["profile9", "group32", "image35"],
  group32: ["group32", "image35"],
  image35: ["image35"],
  profile10: ["profile10", "group33", "image36"],
  group33: ["group33", "image36"],
  image36: ["image36"],
  profile11: ["profile11", "group34", "image37"],
  group34: ["group34", "image37"],
  image37: ["image37"],
  profile12: ["profile12", "group35", "image38"],
  group35: ["group35", "image38"],
  image38: ["image38"],
  union1: ["union1"],
  union8: ["union8"],
  union3: ["union3"],
  union9: ["union9"],
  union5: ["union5"],
  union10: ["union10"],
  union2: ["union2"],
  union11: ["union11"],
  union4: ["union4"],
  union12: ["union12"],
  union6: ["union6"],
  union13: ["union13"],
  union7: ["union7"],
  union14: ["union14"],
  rectangle21: ["rectangle21"],
  group20: ["group20", "rectangle18"],
  rectangle18: ["rectangle18"],
  губопик: ["губопик"],
  group36: ["group36"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPeoplePage__ArgProps,
      internalVariantPropNames: PlasmicPeoplePage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicPeoplePage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPeoplePage";
  } else {
    func.displayName = `PlasmicPeoplePage.${nodeName}`;
  }
  return func;
}

export const PlasmicPeoplePage = Object.assign(
  // Top-level PlasmicPeoplePage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    peoplePageDesktop: makeNodeComponent("peoplePageDesktop"),
    photo202108171656131: makeNodeComponent("photo202108171656131"),
    group8: makeNodeComponent("group8"),
    group21: makeNodeComponent("group21"),
    group1: makeNodeComponent("group1"),
    verify1: makeNodeComponent("verify1"),
    rectangle3: makeNodeComponent("rectangle3"),
    group10: makeNodeComponent("group10"),
    profile: makeNodeComponent("profile"),
    group24: makeNodeComponent("group24"),
    image27: makeNodeComponent("image27"),
    profile2: makeNodeComponent("profile2"),
    group25: makeNodeComponent("group25"),
    image28: makeNodeComponent("image28"),
    profile3: makeNodeComponent("profile3"),
    group26: makeNodeComponent("group26"),
    image29: makeNodeComponent("image29"),
    profile4: makeNodeComponent("profile4"),
    group27: makeNodeComponent("group27"),
    image30: makeNodeComponent("image30"),
    profile5: makeNodeComponent("profile5"),
    group28: makeNodeComponent("group28"),
    image31: makeNodeComponent("image31"),
    profile6: makeNodeComponent("profile6"),
    group29: makeNodeComponent("group29"),
    image32: makeNodeComponent("image32"),
    profile7: makeNodeComponent("profile7"),
    group30: makeNodeComponent("group30"),
    image33: makeNodeComponent("image33"),
    profile8: makeNodeComponent("profile8"),
    group31: makeNodeComponent("group31"),
    image34: makeNodeComponent("image34"),
    profile9: makeNodeComponent("profile9"),
    group32: makeNodeComponent("group32"),
    image35: makeNodeComponent("image35"),
    profile10: makeNodeComponent("profile10"),
    group33: makeNodeComponent("group33"),
    image36: makeNodeComponent("image36"),
    profile11: makeNodeComponent("profile11"),
    group34: makeNodeComponent("group34"),
    image37: makeNodeComponent("image37"),
    profile12: makeNodeComponent("profile12"),
    group35: makeNodeComponent("group35"),
    image38: makeNodeComponent("image38"),
    union1: makeNodeComponent("union1"),
    union8: makeNodeComponent("union8"),
    union3: makeNodeComponent("union3"),
    union9: makeNodeComponent("union9"),
    union5: makeNodeComponent("union5"),
    union10: makeNodeComponent("union10"),
    union2: makeNodeComponent("union2"),
    union11: makeNodeComponent("union11"),
    union4: makeNodeComponent("union4"),
    union12: makeNodeComponent("union12"),
    union6: makeNodeComponent("union6"),
    union13: makeNodeComponent("union13"),
    union7: makeNodeComponent("union7"),
    union14: makeNodeComponent("union14"),
    rectangle21: makeNodeComponent("rectangle21"),
    group20: makeNodeComponent("group20"),
    rectangle18: makeNodeComponent("rectangle18"),
    губопик: makeNodeComponent("губопик"),
    group36: makeNodeComponent("group36"),
    // Metadata about props expected for PlasmicPeoplePage
    internalVariantProps: PlasmicPeoplePage__VariantProps,
    internalArgProps: PlasmicPeoplePage__ArgProps
  }
);

export default PlasmicPeoplePage;
/* prettier-ignore-end */
