// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iw4cFYZtgxW7YvDehgMC47
// Component: Wda2Kcuudt
import * as React from "react";
import Head from "next/head";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_project_web.module.css"; // plasmic-import: iw4cFYZtgxW7YvDehgMC47/projectcss
import * as sty from "./PlasmicMainPage.module.css"; // plasmic-import: Wda2Kcuudt/css
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: 4NZJoj-fIt/icon
import Line9Icon from "./icons/PlasmicIcon__Line9"; // plasmic-import: QdSNciHXdvM/icon
import Line4Icon from "./icons/PlasmicIcon__Line4"; // plasmic-import: vY-U8OLG9IH/icon
import Line3Icon from "./icons/PlasmicIcon__Line3"; // plasmic-import: LvtI6YAzhDC/icon
import Line8Icon from "./icons/PlasmicIcon__Line8"; // plasmic-import: OWLbkpHPcZo/icon
import Polygon1Icon from "./icons/PlasmicIcon__Polygon1"; // plasmic-import: QaRBHQulwLs/icon
import Rectangle20Icon from "./icons/PlasmicIcon__Rectangle20"; // plasmic-import: zWq4rB1ZbJo/icon
import Arrow2Icon from "./icons/PlasmicIcon__Arrow2"; // plasmic-import: d9dK44K72X2/icon

export const PlasmicMainPage__VariantProps = new Array();

export const PlasmicMainPage__ArgProps = new Array();

function PlasmicMainPage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"mainPageDesktop"}
            data-plasmic-override={overrides.mainPageDesktop}
            className={classNames(defaultcss.all, sty.mainPageDesktop)}
          >
            <div
              data-plasmic-name={"logo"}
              data-plasmic-override={overrides.logo}
              className={classNames(defaultcss.all, sty.logo, "logo")}
              id={"logoMainPage"}
            />

            <Line1Icon
              data-plasmic-name={"devidingLineOne"}
              data-plasmic-override={overrides.devidingLineOne}
              className={classNames(
                defaultcss.all,
                sty.devidingLineOne,
                "devidingLine"
              )}
              id={"devidingLineOne"}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__vLakP)}
              role={"img"}
            />

            <Line1Icon
              data-plasmic-name={"devidingLineTwo"}
              data-plasmic-override={overrides.devidingLineTwo}
              className={classNames(
                defaultcss.all,
                sty.devidingLineTwo,
                "devidingLine"
              )}
              id={"devidingLineTwo"}
              role={"img"}
            />

            <Line9Icon
              className={classNames(defaultcss.all, sty.svg__l65Wj)}
              role={"img"}
            />

            <Line9Icon
              className={classNames(defaultcss.all, sty.svg__q3Khb)}
              role={"img"}
            />

            <Line4Icon
              className={classNames(defaultcss.all, sty.svg__lLmHl)}
              role={"img"}
            />

            <Line3Icon
              data-plasmic-name={"headerUnderlineLastNews"}
              data-plasmic-override={overrides.headerUnderlineLastNews}
              className={classNames(
                defaultcss.all,
                sty.headerUnderlineLastNews,
                "headerUnderlineLastNews"
              )}
              id={"headerUnderlineLastNews"}
              role={"img"}
            />

            <Line8Icon
              data-plasmic-name={"underlinePartners"}
              data-plasmic-override={overrides.underlinePartners}
              className={classNames(defaultcss.all, sty.underlinePartners)}
              role={"img"}
            />

            <div
              data-plasmic-name={"menuItems"}
              data-plasmic-override={overrides.menuItems}
              className={classNames(defaultcss.all, sty.menuItems, "menuItems")}
              id={"menuItemsMainPage"}
            >
              <div
                data-plasmic-name={"aboutMenuItem"}
                data-plasmic-override={overrides.aboutMenuItem}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.aboutMenuItem,
                  "chooseRegionIcon"
                )}
                id={"chooseRegionIconMainPage"}
              >
                {"О ПРОЕКТЕ"}
              </div>

              <div
                data-plasmic-name={"donateMenuItem"}
                data-plasmic-override={overrides.donateMenuItem}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.donateMenuItem,
                  "donateMenuItem"
                )}
                id={"donateMenuItemMainPage"}
              >
                {"ПОДДЕРЖАТЬ"}
              </div>

              <div
                data-plasmic-name={"peopleMenuItem"}
                data-plasmic-override={overrides.peopleMenuItem}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.peopleMenuItem,
                  "PeopleMenuItem"
                )}
                id={"PeopleMenuItemMainPage"}
              >
                {"ЛЮДИ"}
              </div>

              <div
                data-plasmic-name={"newsMenuItem"}
                data-plasmic-override={overrides.newsMenuItem}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.newsMenuItem,
                  "newsMenuItem"
                )}
                id={"newsMenuItemMainPage"}
              >
                {"НОВОСТИ"}
              </div>

              <div
                data-plasmic-name={"mapMenuItem"}
                data-plasmic-override={overrides.mapMenuItem}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.mapMenuItem,
                  "mapMenuItem"
                )}
                id={"mapMenuItemMainPage"}
              >
                {"КАРТА ПРЕСТУПНИКОВ"}
              </div>
            </div>

            <div
              data-plasmic-name={"searchIcon"}
              data-plasmic-override={overrides.searchIcon}
              className={classNames(
                defaultcss.all,
                sty.searchIcon,
                "searchIcon"
              )}
              id={"searchIconMainPage"}
            >
              <div
                data-plasmic-name={"finder"}
                data-plasmic-override={overrides.finder}
                className={classNames(defaultcss.all, sty.finder)}
              />

              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(defaultcss.all, sty.rectangle3)}
              />
            </div>

            <div
              data-plasmic-name={"group10"}
              data-plasmic-override={overrides.group10}
              className={classNames(defaultcss.all, sty.group10)}
            >
              <div
                data-plasmic-name={"chooseRegionButton"}
                data-plasmic-override={overrides.chooseRegionButton}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.chooseRegionButton,
                  "chooseRegionButton"
                )}
                id={"chooseRegionButtonMainPage"}
              >
                {"Выбрать регион"}
              </div>

              <Polygon1Icon
                data-plasmic-name={"chooseRegionIcon"}
                data-plasmic-override={overrides.chooseRegionIcon}
                className={classNames(
                  defaultcss.all,
                  sty.chooseRegionIcon,
                  "chooseRegionIcon"
                )}
                id={"chooseRegionIconMainPage"}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"lastNewsHeader"}
              data-plasmic-override={overrides.lastNewsHeader}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.lastNewsHeader,
                "lastNewsHeader"
              )}
              id={"lastNewsHeaderMainPage"}
            >
              {"ПОСЛЕДНИЕ НОВОСТИ"}
            </div>

            <div
              data-plasmic-name={"partnerstext"}
              data-plasmic-override={overrides.partnerstext}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.partnerstext
              )}
            >
              {"НАШИ ПАРТНЕРЫ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__hyyQx
              )}
            >
              {"ИХ ЧАСТО ИЩУТ"}
            </div>

            <div
              data-plasmic-name={"profile"}
              data-plasmic-override={overrides.profile}
              className={classNames(defaultcss.all, sty.profile)}
            >
              <div
                data-plasmic-name={"group24"}
                data-plasmic-override={overrides.group24}
                className={classNames(defaultcss.all, sty.group24)}
              >
                <div
                  data-plasmic-name={"image27"}
                  data-plasmic-override={overrides.image27}
                  className={classNames(defaultcss.all, sty.image27)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__ocQu3)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__lGy6B
                )}
              >
                {"Милиционер"}
              </div>

              <div
                data-plasmic-name={"header7"}
                data-plasmic-override={overrides.header7}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.header7
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile2"}
              data-plasmic-override={overrides.profile2}
              className={classNames(defaultcss.all, sty.profile2)}
            >
              <div
                data-plasmic-name={"group25"}
                data-plasmic-override={overrides.group25}
                className={classNames(defaultcss.all, sty.group25)}
              >
                <div
                  data-plasmic-name={"image28"}
                  data-plasmic-override={overrides.image28}
                  className={classNames(defaultcss.all, sty.image28)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__ppFZy)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__j8DOl
                )}
              >
                {"Милиционер"}
              </div>

              <div
                data-plasmic-name={"header8"}
                data-plasmic-override={overrides.header8}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.header8
                )}
              >
                {"Терехов Александр Александрович"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile3"}
              data-plasmic-override={overrides.profile3}
              className={classNames(defaultcss.all, sty.profile3)}
            >
              <div
                data-plasmic-name={"group23"}
                data-plasmic-override={overrides.group23}
                className={classNames(defaultcss.all, sty.group23)}
              >
                <div
                  data-plasmic-name={"image26"}
                  data-plasmic-override={overrides.image26}
                  className={classNames(defaultcss.all, sty.image26)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__sxkD)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___6Fays
                )}
              >
                {"Милиционер"}
              </div>

              <div
                data-plasmic-name={"header9"}
                data-plasmic-override={overrides.header9}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.header9
                )}
              >
                {"Занько Дмитрий Александрович"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile4"}
              data-plasmic-override={overrides.profile4}
              className={classNames(defaultcss.all, sty.profile4)}
            >
              <div
                data-plasmic-name={"group26"}
                data-plasmic-override={overrides.group26}
                className={classNames(defaultcss.all, sty.group26)}
              >
                <div
                  data-plasmic-name={"image29"}
                  data-plasmic-override={overrides.image29}
                  className={classNames(defaultcss.all, sty.image29)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__utTXf)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__r7Wd6
                )}
              >
                {"Милиционер"}
              </div>

              <div
                data-plasmic-name={"header10"}
                data-plasmic-override={overrides.header10}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.header10
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile5"}
              data-plasmic-override={overrides.profile5}
              className={classNames(defaultcss.all, sty.profile5)}
            >
              <div
                data-plasmic-name={"group27"}
                data-plasmic-override={overrides.group27}
                className={classNames(defaultcss.all, sty.group27)}
              >
                <div
                  data-plasmic-name={"image30"}
                  data-plasmic-override={overrides.image30}
                  className={classNames(defaultcss.all, sty.image30)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg___4BIqW)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___4QEvH
                )}
              >
                {"Милиционер"}
              </div>

              <div
                data-plasmic-name={"header11"}
                data-plasmic-override={overrides.header11}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.header11
                )}
              >
                {"Терехов Александр Александрович"}
              </div>
            </div>

            <div
              data-plasmic-name={"disclaimerText"}
              data-plasmic-override={overrides.disclaimerText}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.disclaimerText,
                "disclaimerText"
              )}
              id={"disclaimerTextFirst"}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/ видео подтверждения и тра-тра-та наш бот @botbotbot"
              }
            </div>

            <div
              data-plasmic-name={"group28"}
              data-plasmic-override={overrides.group28}
              className={classNames(defaultcss.all, sty.group28)}
            >
              <div
                data-plasmic-name={"moreNewsButton"}
                data-plasmic-override={overrides.moreNewsButton}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.moreNewsButton
                )}
              >
                {"Больше новостей"}
              </div>

              <Arrow2Icon
                data-plasmic-name={"arrowButton"}
                data-plasmic-override={overrides.arrowButton}
                className={classNames(defaultcss.all, sty.arrowButton)}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"union1"}
              data-plasmic-override={overrides.union1}
              className={classNames(defaultcss.all, sty.union1)}
            />

            <div
              data-plasmic-name={"union8"}
              data-plasmic-override={overrides.union8}
              className={classNames(defaultcss.all, sty.union8)}
            />

            <div
              data-plasmic-name={"union3"}
              data-plasmic-override={overrides.union3}
              className={classNames(defaultcss.all, sty.union3)}
            />

            <div
              data-plasmic-name={"union9"}
              data-plasmic-override={overrides.union9}
              className={classNames(defaultcss.all, sty.union9)}
            />

            <div
              data-plasmic-name={"union5"}
              data-plasmic-override={overrides.union5}
              className={classNames(defaultcss.all, sty.union5)}
            />

            <div
              data-plasmic-name={"union10"}
              data-plasmic-override={overrides.union10}
              className={classNames(defaultcss.all, sty.union10)}
            />

            <div
              data-plasmic-name={"union2"}
              data-plasmic-override={overrides.union2}
              className={classNames(defaultcss.all, sty.union2)}
            />

            <div
              data-plasmic-name={"union11"}
              data-plasmic-override={overrides.union11}
              className={classNames(defaultcss.all, sty.union11)}
            />

            <div
              data-plasmic-name={"union4"}
              data-plasmic-override={overrides.union4}
              className={classNames(defaultcss.all, sty.union4)}
            />

            <div
              data-plasmic-name={"union12"}
              data-plasmic-override={overrides.union12}
              className={classNames(defaultcss.all, sty.union12)}
            />

            <div
              data-plasmic-name={"union6"}
              data-plasmic-override={overrides.union6}
              className={classNames(defaultcss.all, sty.union6)}
            />

            <div
              data-plasmic-name={"union13"}
              data-plasmic-override={overrides.union13}
              className={classNames(defaultcss.all, sty.union13)}
            />

            <div
              data-plasmic-name={"union7"}
              data-plasmic-override={overrides.union7}
              className={classNames(defaultcss.all, sty.union7)}
            />

            <div
              data-plasmic-name={"union14"}
              data-plasmic-override={overrides.union14}
              className={classNames(defaultcss.all, sty.union14)}
            />

            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(defaultcss.all, sty.footer)}
            />

            <div
              data-plasmic-name={"footerTextDescription"}
              data-plasmic-override={overrides.footerTextDescription}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.footerTextDescription
              )}
            >
              {
                "Публикуемые личные данные получены из открытых источников методом социальной инженерии или же непосредственно от читателей. Данные публикуются исключительно с целью упрощения последующего расследования преступлений. \n\nКоманда чкб не призывает к насилию. выступает против любого вида дискриминации и порицает разжигание социальной вражды."
              }
            </div>

            <div
              data-plasmic-name={"footerTextButton"}
              data-plasmic-override={overrides.footerTextButton}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.footerTextButton
              )}
            >
              {"Связаться с нами через бота"}
            </div>

            <div
              data-plasmic-name={"footerTextButton2"}
              data-plasmic-override={overrides.footerTextButton2}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.footerTextButton2
              )}
            >
              {"Ошибка в тексте?"}
            </div>

            <div
              data-plasmic-name={"footerText"}
              data-plasmic-override={overrides.footerText}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.footerText
              )}
            >
              {"ЧЕРНАЯ КНИГА БЕЛАРУСИ"}
            </div>

            <div
              data-plasmic-name={"group20"}
              data-plasmic-override={overrides.group20}
              className={classNames(defaultcss.all, sty.group20)}
            >
              <div
                data-plasmic-name={"footerTextButton3"}
                data-plasmic-override={overrides.footerTextButton3}
                className={classNames(defaultcss.all, sty.footerTextButton3)}
              />
            </div>

            <div
              data-plasmic-name={"disclaimerText2"}
              data-plasmic-override={overrides.disclaimerText2}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.disclaimerText2,
                "disclaimerText"
              )}
              id={"disclaimerTextSecond"}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/"
              }
            </div>

            <div
              data-plasmic-name={"group29"}
              data-plasmic-override={overrides.group29}
              className={classNames(defaultcss.all, sty.group29)}
            >
              <div
                data-plasmic-name={"header4"}
                data-plasmic-override={overrides.header4}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.header4
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text
                )}
              >
                {
                  "Суд города Барановичи вынес решение по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением..."
                }
              </div>

              <div
                data-plasmic-name={"group30"}
                data-plasmic-override={overrides.group30}
                className={classNames(defaultcss.all, sty.group30)}
              >
                <div
                  data-plasmic-name={"newImage"}
                  data-plasmic-override={overrides.newImage}
                  className={classNames(defaultcss.all, sty.newImage)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"group31"}
              data-plasmic-override={overrides.group31}
              className={classNames(defaultcss.all, sty.group31)}
            >
              <div
                data-plasmic-name={"header5"}
                data-plasmic-override={overrides.header5}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.header5
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                data-plasmic-name={"text2"}
                data-plasmic-override={overrides.text2}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text2
                )}
              >
                {
                  "Суд города Барановичи вынес решение по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением..."
                }
              </div>

              <div
                data-plasmic-name={"group32"}
                data-plasmic-override={overrides.group32}
                className={classNames(defaultcss.all, sty.group32)}
              >
                <div
                  data-plasmic-name={"newImage2"}
                  data-plasmic-override={overrides.newImage2}
                  className={classNames(defaultcss.all, sty.newImage2)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"group33"}
              data-plasmic-override={overrides.group33}
              className={classNames(defaultcss.all, sty.group33)}
            >
              <div
                data-plasmic-name={"header6"}
                data-plasmic-override={overrides.header6}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.header6
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                data-plasmic-name={"text3"}
                data-plasmic-override={overrides.text3}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text3
                )}
              >
                {
                  "Суд города Барановичи вынес решение по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением..."
                }
              </div>

              <div
                data-plasmic-name={"group34"}
                data-plasmic-override={overrides.group34}
                className={classNames(defaultcss.all, sty.group34)}
              >
                <div
                  data-plasmic-name={"newImage3"}
                  data-plasmic-override={overrides.newImage3}
                  className={classNames(defaultcss.all, sty.newImage3)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"group35"}
              data-plasmic-override={overrides.group35}
              className={classNames(defaultcss.all, sty.group35)}
            >
              <div
                data-plasmic-name={"header3"}
                data-plasmic-override={overrides.header3}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.header3
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                data-plasmic-name={"description"}
                data-plasmic-override={overrides.description}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.description
                )}
              >
                {
                  'Суд города Барановичи вынес решение (https://t.me/viasna96/6750) по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением Караева (https://t.me/BlackBookBelarus/2032) он написал комментарий “ч*рка гребаный”. Этим он "публично оскорбил представителя власти в связи с выполнением им служебных обязанностей"...'
                }
              </div>

              <div
                data-plasmic-name={"date3"}
                data-plasmic-override={overrides.date3}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.date3
                )}
              >
                {"21.08.2021"}
              </div>

              <div
                data-plasmic-name={"group36"}
                data-plasmic-override={overrides.group36}
                className={classNames(defaultcss.all, sty.group36)}
              >
                <div
                  data-plasmic-name={"newImage4"}
                  data-plasmic-override={overrides.newImage4}
                  className={classNames(defaultcss.all, sty.newImage4)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"news2"}
              data-plasmic-override={overrides.news2}
              className={classNames(defaultcss.all, sty.news2)}
            >
              <div
                data-plasmic-name={"header2"}
                data-plasmic-override={overrides.header2}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.header2
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                data-plasmic-name={"description2"}
                data-plasmic-override={overrides.description2}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.description2
                )}
              >
                {
                  "Суд города Барановичи вынес решение (https://t.me/viasna96/6750) по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением Караева"
                }
              </div>

              <div
                data-plasmic-name={"date2"}
                data-plasmic-override={overrides.date2}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.date2
                )}
              >
                {"21.08.2021"}
              </div>

              <div
                data-plasmic-name={"group38"}
                data-plasmic-override={overrides.group38}
                className={classNames(defaultcss.all, sty.group38)}
              >
                <div
                  data-plasmic-name={"newImage5"}
                  data-plasmic-override={overrides.newImage5}
                  className={classNames(defaultcss.all, sty.newImage5)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"news"}
              data-plasmic-override={overrides.news}
              className={classNames(defaultcss.all, sty.news)}
            >
              <div
                data-plasmic-name={"header"}
                data-plasmic-override={overrides.header}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.header
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                data-plasmic-name={"description3"}
                data-plasmic-override={overrides.description3}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.description3
                )}
              >
                {
                  'Суд города Барановичи вынес решение (https://t.me/viasna96/6750) по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением Караева (https://t.me/BlackBookBelarus/2032) он написал комментарий “ч*рка гребаный”. Этим он "публично оскорбил представителя власти в связи с выполнением им служебных обязанностей"...'
                }
              </div>

              <div
                data-plasmic-name={"date"}
                data-plasmic-override={overrides.date}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.date
                )}
              >
                {"21.08.2021"}
              </div>

              <div
                data-plasmic-name={"group40"}
                data-plasmic-override={overrides.group40}
                className={classNames(defaultcss.all, sty.group40)}
              >
                <div
                  data-plasmic-name={"newImage6"}
                  data-plasmic-override={overrides.newImage6}
                  className={classNames(defaultcss.all, sty.newImage6)}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "mainPageDesktop",
    "logo",
    "devidingLineOne",
    "devidingLineTwo",
    "headerUnderlineLastNews",
    "underlinePartners",
    "menuItems",
    "aboutMenuItem",
    "donateMenuItem",
    "peopleMenuItem",
    "newsMenuItem",
    "mapMenuItem",
    "searchIcon",
    "finder",
    "rectangle3",
    "group10",
    "chooseRegionButton",
    "chooseRegionIcon",
    "lastNewsHeader",
    "partnerstext",
    "profile",
    "group24",
    "image27",
    "header7",
    "profile2",
    "group25",
    "image28",
    "header8",
    "profile3",
    "group23",
    "image26",
    "header9",
    "profile4",
    "group26",
    "image29",
    "header10",
    "profile5",
    "group27",
    "image30",
    "header11",
    "disclaimerText",
    "group28",
    "moreNewsButton",
    "arrowButton",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "footer",
    "footerTextDescription",
    "footerTextButton",
    "footerTextButton2",
    "footerText",
    "group20",
    "footerTextButton3",
    "disclaimerText2",
    "group29",
    "header4",
    "text",
    "group30",
    "newImage",
    "group31",
    "header5",
    "text2",
    "group32",
    "newImage2",
    "group33",
    "header6",
    "text3",
    "group34",
    "newImage3",
    "group35",
    "header3",
    "description",
    "date3",
    "group36",
    "newImage4",
    "news2",
    "header2",
    "description2",
    "date2",
    "group38",
    "newImage5",
    "news",
    "header",
    "description3",
    "date",
    "group40",
    "newImage6"
  ],

  mainPageDesktop: [
    "mainPageDesktop",
    "logo",
    "devidingLineOne",
    "devidingLineTwo",
    "headerUnderlineLastNews",
    "underlinePartners",
    "menuItems",
    "aboutMenuItem",
    "donateMenuItem",
    "peopleMenuItem",
    "newsMenuItem",
    "mapMenuItem",
    "searchIcon",
    "finder",
    "rectangle3",
    "group10",
    "chooseRegionButton",
    "chooseRegionIcon",
    "lastNewsHeader",
    "partnerstext",
    "profile",
    "group24",
    "image27",
    "header7",
    "profile2",
    "group25",
    "image28",
    "header8",
    "profile3",
    "group23",
    "image26",
    "header9",
    "profile4",
    "group26",
    "image29",
    "header10",
    "profile5",
    "group27",
    "image30",
    "header11",
    "disclaimerText",
    "group28",
    "moreNewsButton",
    "arrowButton",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "footer",
    "footerTextDescription",
    "footerTextButton",
    "footerTextButton2",
    "footerText",
    "group20",
    "footerTextButton3",
    "disclaimerText2",
    "group29",
    "header4",
    "text",
    "group30",
    "newImage",
    "group31",
    "header5",
    "text2",
    "group32",
    "newImage2",
    "group33",
    "header6",
    "text3",
    "group34",
    "newImage3",
    "group35",
    "header3",
    "description",
    "date3",
    "group36",
    "newImage4",
    "news2",
    "header2",
    "description2",
    "date2",
    "group38",
    "newImage5",
    "news",
    "header",
    "description3",
    "date",
    "group40",
    "newImage6"
  ],

  logo: ["logo"],
  devidingLineOne: ["devidingLineOne"],
  devidingLineTwo: ["devidingLineTwo"],
  headerUnderlineLastNews: ["headerUnderlineLastNews"],
  underlinePartners: ["underlinePartners"],
  menuItems: [
    "menuItems",
    "aboutMenuItem",
    "donateMenuItem",
    "peopleMenuItem",
    "newsMenuItem",
    "mapMenuItem"
  ],

  aboutMenuItem: ["aboutMenuItem"],
  donateMenuItem: ["donateMenuItem"],
  peopleMenuItem: ["peopleMenuItem"],
  newsMenuItem: ["newsMenuItem"],
  mapMenuItem: ["mapMenuItem"],
  searchIcon: ["searchIcon", "finder", "rectangle3"],
  finder: ["finder"],
  rectangle3: ["rectangle3"],
  group10: ["group10", "chooseRegionButton", "chooseRegionIcon"],
  chooseRegionButton: ["chooseRegionButton"],
  chooseRegionIcon: ["chooseRegionIcon"],
  lastNewsHeader: ["lastNewsHeader"],
  partnerstext: ["partnerstext"],
  profile: ["profile", "group24", "image27", "header7"],
  group24: ["group24", "image27"],
  image27: ["image27"],
  header7: ["header7"],
  profile2: ["profile2", "group25", "image28", "header8"],
  group25: ["group25", "image28"],
  image28: ["image28"],
  header8: ["header8"],
  profile3: ["profile3", "group23", "image26", "header9"],
  group23: ["group23", "image26"],
  image26: ["image26"],
  header9: ["header9"],
  profile4: ["profile4", "group26", "image29", "header10"],
  group26: ["group26", "image29"],
  image29: ["image29"],
  header10: ["header10"],
  profile5: ["profile5", "group27", "image30", "header11"],
  group27: ["group27", "image30"],
  image30: ["image30"],
  header11: ["header11"],
  disclaimerText: ["disclaimerText"],
  group28: ["group28", "moreNewsButton", "arrowButton"],
  moreNewsButton: ["moreNewsButton"],
  arrowButton: ["arrowButton"],
  union1: ["union1"],
  union8: ["union8"],
  union3: ["union3"],
  union9: ["union9"],
  union5: ["union5"],
  union10: ["union10"],
  union2: ["union2"],
  union11: ["union11"],
  union4: ["union4"],
  union12: ["union12"],
  union6: ["union6"],
  union13: ["union13"],
  union7: ["union7"],
  union14: ["union14"],
  footer: ["footer"],
  footerTextDescription: ["footerTextDescription"],
  footerTextButton: ["footerTextButton"],
  footerTextButton2: ["footerTextButton2"],
  footerText: ["footerText"],
  group20: ["group20", "footerTextButton3"],
  footerTextButton3: ["footerTextButton3"],
  disclaimerText2: ["disclaimerText2"],
  group29: ["group29", "header4", "text", "group30", "newImage"],
  header4: ["header4"],
  text: ["text"],
  group30: ["group30", "newImage"],
  newImage: ["newImage"],
  group31: ["group31", "header5", "text2", "group32", "newImage2"],
  header5: ["header5"],
  text2: ["text2"],
  group32: ["group32", "newImage2"],
  newImage2: ["newImage2"],
  group33: ["group33", "header6", "text3", "group34", "newImage3"],
  header6: ["header6"],
  text3: ["text3"],
  group34: ["group34", "newImage3"],
  newImage3: ["newImage3"],
  group35: [
    "group35",
    "header3",
    "description",
    "date3",
    "group36",
    "newImage4"
  ],

  header3: ["header3"],
  description: ["description"],
  date3: ["date3"],
  group36: ["group36", "newImage4"],
  newImage4: ["newImage4"],
  news2: ["news2", "header2", "description2", "date2", "group38", "newImage5"],
  header2: ["header2"],
  description2: ["description2"],
  date2: ["date2"],
  group38: ["group38", "newImage5"],
  newImage5: ["newImage5"],
  news: ["news", "header", "description3", "date", "group40", "newImage6"],
  header: ["header"],
  description3: ["description3"],
  date: ["date"],
  group40: ["group40", "newImage6"],
  newImage6: ["newImage6"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMainPage__ArgProps,
      internalVariantPropNames: PlasmicMainPage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicMainPage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMainPage";
  } else {
    func.displayName = `PlasmicMainPage.${nodeName}`;
  }
  return func;
}

export const PlasmicMainPage = Object.assign(
  // Top-level PlasmicMainPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mainPageDesktop: makeNodeComponent("mainPageDesktop"),
    logo: makeNodeComponent("logo"),
    devidingLineOne: makeNodeComponent("devidingLineOne"),
    devidingLineTwo: makeNodeComponent("devidingLineTwo"),
    headerUnderlineLastNews: makeNodeComponent("headerUnderlineLastNews"),
    underlinePartners: makeNodeComponent("underlinePartners"),
    menuItems: makeNodeComponent("menuItems"),
    aboutMenuItem: makeNodeComponent("aboutMenuItem"),
    donateMenuItem: makeNodeComponent("donateMenuItem"),
    peopleMenuItem: makeNodeComponent("peopleMenuItem"),
    newsMenuItem: makeNodeComponent("newsMenuItem"),
    mapMenuItem: makeNodeComponent("mapMenuItem"),
    searchIcon: makeNodeComponent("searchIcon"),
    finder: makeNodeComponent("finder"),
    rectangle3: makeNodeComponent("rectangle3"),
    group10: makeNodeComponent("group10"),
    chooseRegionButton: makeNodeComponent("chooseRegionButton"),
    chooseRegionIcon: makeNodeComponent("chooseRegionIcon"),
    lastNewsHeader: makeNodeComponent("lastNewsHeader"),
    partnerstext: makeNodeComponent("partnerstext"),
    profile: makeNodeComponent("profile"),
    group24: makeNodeComponent("group24"),
    image27: makeNodeComponent("image27"),
    header7: makeNodeComponent("header7"),
    profile2: makeNodeComponent("profile2"),
    group25: makeNodeComponent("group25"),
    image28: makeNodeComponent("image28"),
    header8: makeNodeComponent("header8"),
    profile3: makeNodeComponent("profile3"),
    group23: makeNodeComponent("group23"),
    image26: makeNodeComponent("image26"),
    header9: makeNodeComponent("header9"),
    profile4: makeNodeComponent("profile4"),
    group26: makeNodeComponent("group26"),
    image29: makeNodeComponent("image29"),
    header10: makeNodeComponent("header10"),
    profile5: makeNodeComponent("profile5"),
    group27: makeNodeComponent("group27"),
    image30: makeNodeComponent("image30"),
    header11: makeNodeComponent("header11"),
    disclaimerText: makeNodeComponent("disclaimerText"),
    group28: makeNodeComponent("group28"),
    moreNewsButton: makeNodeComponent("moreNewsButton"),
    arrowButton: makeNodeComponent("arrowButton"),
    union1: makeNodeComponent("union1"),
    union8: makeNodeComponent("union8"),
    union3: makeNodeComponent("union3"),
    union9: makeNodeComponent("union9"),
    union5: makeNodeComponent("union5"),
    union10: makeNodeComponent("union10"),
    union2: makeNodeComponent("union2"),
    union11: makeNodeComponent("union11"),
    union4: makeNodeComponent("union4"),
    union12: makeNodeComponent("union12"),
    union6: makeNodeComponent("union6"),
    union13: makeNodeComponent("union13"),
    union7: makeNodeComponent("union7"),
    union14: makeNodeComponent("union14"),
    footer: makeNodeComponent("footer"),
    footerTextDescription: makeNodeComponent("footerTextDescription"),
    footerTextButton: makeNodeComponent("footerTextButton"),
    footerTextButton2: makeNodeComponent("footerTextButton2"),
    footerText: makeNodeComponent("footerText"),
    group20: makeNodeComponent("group20"),
    footerTextButton3: makeNodeComponent("footerTextButton3"),
    disclaimerText2: makeNodeComponent("disclaimerText2"),
    group29: makeNodeComponent("group29"),
    header4: makeNodeComponent("header4"),
    text: makeNodeComponent("text"),
    group30: makeNodeComponent("group30"),
    newImage: makeNodeComponent("newImage"),
    group31: makeNodeComponent("group31"),
    header5: makeNodeComponent("header5"),
    text2: makeNodeComponent("text2"),
    group32: makeNodeComponent("group32"),
    newImage2: makeNodeComponent("newImage2"),
    group33: makeNodeComponent("group33"),
    header6: makeNodeComponent("header6"),
    text3: makeNodeComponent("text3"),
    group34: makeNodeComponent("group34"),
    newImage3: makeNodeComponent("newImage3"),
    group35: makeNodeComponent("group35"),
    header3: makeNodeComponent("header3"),
    description: makeNodeComponent("description"),
    date3: makeNodeComponent("date3"),
    group36: makeNodeComponent("group36"),
    newImage4: makeNodeComponent("newImage4"),
    news2: makeNodeComponent("news2"),
    header2: makeNodeComponent("header2"),
    description2: makeNodeComponent("description2"),
    date2: makeNodeComponent("date2"),
    group38: makeNodeComponent("group38"),
    newImage5: makeNodeComponent("newImage5"),
    news: makeNodeComponent("news"),
    header: makeNodeComponent("header"),
    description3: makeNodeComponent("description3"),
    date: makeNodeComponent("date"),
    group40: makeNodeComponent("group40"),
    newImage6: makeNodeComponent("newImage6"),
    // Metadata about props expected for PlasmicMainPage
    internalVariantProps: PlasmicMainPage__VariantProps,
    internalArgProps: PlasmicMainPage__ArgProps
  }
);

export default PlasmicMainPage;
/* prettier-ignore-end */
