// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iw4cFYZtgxW7YvDehgMC47
// Component: Sd2SKH8nj-T
import * as React from "react";
import Head from "next/head";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_project_web.module.css"; // plasmic-import: iw4cFYZtgxW7YvDehgMC47/projectcss
import * as sty from "./PlasmicFindResults.module.css"; // plasmic-import: Sd2SKH8nj-T/css
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: RWzvUW32AX/icon
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: 4NZJoj-fIt/icon
import Line4Icon from "./icons/PlasmicIcon__Line4"; // plasmic-import: vY-U8OLG9IH/icon
import Line7Icon from "./icons/PlasmicIcon__Line7"; // plasmic-import: CQy-DIM1o6/icon
import Line8Icon from "./icons/PlasmicIcon__Line8"; // plasmic-import: OWLbkpHPcZo/icon
import Polygon1Icon from "./icons/PlasmicIcon__Polygon1"; // plasmic-import: QaRBHQulwLs/icon
import Rectangle20Icon from "./icons/PlasmicIcon__Rectangle20"; // plasmic-import: zWq4rB1ZbJo/icon
import Line15Icon from "./icons/PlasmicIcon__Line15"; // plasmic-import: iescvvzXIqS/icon
import Line16Icon from "./icons/PlasmicIcon__Line16"; // plasmic-import: tWXvMBeMDbJ/icon
import Arrow2Icon from "./icons/PlasmicIcon__Arrow2"; // plasmic-import: d9dK44K72X2/icon

export const PlasmicFindResults__VariantProps = new Array();

export const PlasmicFindResults__ArgProps = new Array();

function PlasmicFindResults__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"findResultPageDesktop"}
            data-plasmic-override={overrides.findResultPageDesktop}
            className={classNames(defaultcss.all, sty.findResultPageDesktop)}
          >
            {false ? (
              <Line5Icon
                className={classNames(defaultcss.all, sty.svg__b5V5Q)}
                role={"img"}
              />
            ) : null}

            <div
              data-plasmic-name={"photo202108171656131"}
              data-plasmic-override={overrides.photo202108171656131}
              className={classNames(defaultcss.all, sty.photo202108171656131)}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__depI)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__joYh)}
              role={"img"}
            />

            <Line4Icon
              className={classNames(defaultcss.all, sty.svg__wKlZ9)}
              role={"img"}
            />

            <Line7Icon
              className={classNames(defaultcss.all, sty.svg__mDaeg)}
              role={"img"}
            />

            <Line8Icon
              className={classNames(defaultcss.all, sty.svg__s9Xc2)}
              role={"img"}
            />

            <div
              data-plasmic-name={"group8"}
              data-plasmic-override={overrides.group8}
              className={classNames(defaultcss.all, sty.group8)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__wS4Ql
                )}
              >
                {"О ПРОЕКТЕ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__g6MZ8
                )}
              >
                {"ПОДДЕРЖАТЬ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__tRuZu
                )}
              >
                {"ЛЮДИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___1R5Qp
                )}
              >
                {"НОВОСТИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__sbFa6
                )}
              >
                {"КАРТА ПРЕСТУПНИКОВ"}
              </div>
            </div>

            <div
              data-plasmic-name={"group1"}
              data-plasmic-override={overrides.group1}
              className={classNames(defaultcss.all, sty.group1)}
            >
              <div
                data-plasmic-name={"verify1"}
                data-plasmic-override={overrides.verify1}
                className={classNames(defaultcss.all, sty.verify1)}
              />

              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(defaultcss.all, sty.rectangle3)}
              />
            </div>

            <div
              data-plasmic-name={"group10"}
              data-plasmic-override={overrides.group10}
              className={classNames(defaultcss.all, sty.group10)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___9Z47V
                )}
              >
                {"Выбрать регион"}
              </div>

              <Polygon1Icon
                className={classNames(defaultcss.all, sty.svg__kPnNd)}
                role={"img"}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__a2GW
              )}
            >
              {"РЕЗУЛЬТАТЫ ПОИСКА"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__vZzAh
              )}
            >
              {"НАШИ ПАРТНЕРЫ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__v6URi
              )}
            >
              {"ИХ ЧАСТО ИЩУТ"}
            </div>

            <div
              data-plasmic-name={"profile"}
              data-plasmic-override={overrides.profile}
              className={classNames(defaultcss.all, sty.profile)}
            >
              <div
                data-plasmic-name={"group24"}
                data-plasmic-override={overrides.group24}
                className={classNames(defaultcss.all, sty.group24)}
              >
                <div
                  data-plasmic-name={"image27"}
                  data-plasmic-override={overrides.image27}
                  className={classNames(defaultcss.all, sty.image27)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg___8Vigm)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__jIyr
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__cgw3Z
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile2"}
              data-plasmic-override={overrides.profile2}
              className={classNames(defaultcss.all, sty.profile2)}
            >
              <div
                data-plasmic-name={"group25"}
                data-plasmic-override={overrides.group25}
                className={classNames(defaultcss.all, sty.group25)}
              >
                <div
                  data-plasmic-name={"image28"}
                  data-plasmic-override={overrides.image28}
                  className={classNames(defaultcss.all, sty.image28)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__y7Xz1)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__nNsK
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__vAjMb
                )}
              >
                {"Терехов Александр Александрович"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile3"}
              data-plasmic-override={overrides.profile3}
              className={classNames(defaultcss.all, sty.profile3)}
            >
              <div
                data-plasmic-name={"group23"}
                data-plasmic-override={overrides.group23}
                className={classNames(defaultcss.all, sty.group23)}
              >
                <div
                  data-plasmic-name={"image26"}
                  data-plasmic-override={overrides.image26}
                  className={classNames(defaultcss.all, sty.image26)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__lfQ86)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__wlid
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__xwEhl
                )}
              >
                {"Занько Дмитрий Александрович"}
              </div>
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__nby89
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/ видео подтверждения и тра-тра-та наш бот @botbotbot"
              }
            </div>

            <div
              data-plasmic-name={"union1"}
              data-plasmic-override={overrides.union1}
              className={classNames(defaultcss.all, sty.union1)}
            />

            <div
              data-plasmic-name={"union8"}
              data-plasmic-override={overrides.union8}
              className={classNames(defaultcss.all, sty.union8)}
            />

            <div
              data-plasmic-name={"union3"}
              data-plasmic-override={overrides.union3}
              className={classNames(defaultcss.all, sty.union3)}
            />

            <div
              data-plasmic-name={"union9"}
              data-plasmic-override={overrides.union9}
              className={classNames(defaultcss.all, sty.union9)}
            />

            <div
              data-plasmic-name={"union5"}
              data-plasmic-override={overrides.union5}
              className={classNames(defaultcss.all, sty.union5)}
            />

            <div
              data-plasmic-name={"union10"}
              data-plasmic-override={overrides.union10}
              className={classNames(defaultcss.all, sty.union10)}
            />

            <div
              data-plasmic-name={"union2"}
              data-plasmic-override={overrides.union2}
              className={classNames(defaultcss.all, sty.union2)}
            />

            <div
              data-plasmic-name={"union11"}
              data-plasmic-override={overrides.union11}
              className={classNames(defaultcss.all, sty.union11)}
            />

            <div
              data-plasmic-name={"union4"}
              data-plasmic-override={overrides.union4}
              className={classNames(defaultcss.all, sty.union4)}
            />

            <div
              data-plasmic-name={"union12"}
              data-plasmic-override={overrides.union12}
              className={classNames(defaultcss.all, sty.union12)}
            />

            <div
              data-plasmic-name={"union6"}
              data-plasmic-override={overrides.union6}
              className={classNames(defaultcss.all, sty.union6)}
            />

            <div
              data-plasmic-name={"union13"}
              data-plasmic-override={overrides.union13}
              className={classNames(defaultcss.all, sty.union13)}
            />

            <div
              data-plasmic-name={"union7"}
              data-plasmic-override={overrides.union7}
              className={classNames(defaultcss.all, sty.union7)}
            />

            <div
              data-plasmic-name={"union14"}
              data-plasmic-override={overrides.union14}
              className={classNames(defaultcss.all, sty.union14)}
            />

            <div
              data-plasmic-name={"rectangle21"}
              data-plasmic-override={overrides.rectangle21}
              className={classNames(defaultcss.all, sty.rectangle21)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__vo04S
              )}
            >
              {
                "Публикуемые личные данные получены из открытых источников методом социальной инженерии или же непосредственно от читателей. Данные публикуются исключительно с целью упрощения последующего расследования преступлений. \n\nКоманда чкб не призывает к насилию. выступает против любого вида дискриминации и порицает разжигание социальной вражды."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__rEzJ1
              )}
            >
              {"Связаться с нами через бота"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__neYh
              )}
            >
              {"Ошибка в тексте?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox___37Ax2
              )}
            >
              {"ЧЕРНАЯ КНИГА БЕЛАРУСИ"}
            </div>

            <div
              data-plasmic-name={"group20"}
              data-plasmic-override={overrides.group20}
              className={classNames(defaultcss.all, sty.group20)}
            >
              <div
                data-plasmic-name={"rectangle18"}
                data-plasmic-override={overrides.rectangle18}
                className={classNames(defaultcss.all, sty.rectangle18)}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__aznfj
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/"
              }
            </div>

            <div
              data-plasmic-name={"group46"}
              data-plasmic-override={overrides.group46}
              className={classNames(defaultcss.all, sty.group46)}
            >
              <Line15Icon
                className={classNames(defaultcss.all, sty.svg__blJ0)}
                role={"img"}
              />

              <div
                data-plasmic-name={"group45"}
                data-plasmic-override={overrides.group45}
                className={classNames(defaultcss.all, sty.group45)}
              >
                <div
                  data-plasmic-name={"group26"}
                  data-plasmic-override={overrides.group26}
                  className={classNames(defaultcss.all, sty.group26)}
                >
                  <div
                    data-plasmic-name={"image29"}
                    data-plasmic-override={overrides.image29}
                    className={classNames(defaultcss.all, sty.image29)}
                  />
                </div>

                <Rectangle20Icon
                  className={classNames(defaultcss.all, sty.svg___1Ti7G)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__flVdF
                  )}
                >
                  {"Милиционер"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__aj4Nt
                  )}
                >
                  {"Бородич Лина Ивановна"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__cfY7R
                  )}
                >
                  {
                    "12.03.1994\r\n\r\nПомощник прокурора Советского района Минска. юрист 3 класса\r\n\r\nВыступала гособвинителем по делу о клевете в отношении Лукашенко. Минчанина Игоря Ухалюка приговорили...."
                  }
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"group47"}
              data-plasmic-override={overrides.group47}
              className={classNames(defaultcss.all, sty.group47)}
            >
              <Line15Icon
                className={classNames(defaultcss.all, sty.svg__qEsdz)}
                role={"img"}
              />

              <div
                data-plasmic-name={"group48"}
                data-plasmic-override={overrides.group48}
                className={classNames(defaultcss.all, sty.group48)}
              >
                <div
                  data-plasmic-name={"group27"}
                  data-plasmic-override={overrides.group27}
                  className={classNames(defaultcss.all, sty.group27)}
                >
                  <div
                    data-plasmic-name={"image30"}
                    data-plasmic-override={overrides.image30}
                    className={classNames(defaultcss.all, sty.image30)}
                  />
                </div>

                <Rectangle20Icon
                  className={classNames(defaultcss.all, sty.svg__i8M7)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__o3Nfs
                  )}
                >
                  {"Милиционер"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__ivA5H
                  )}
                >
                  {"Бородич Лина Ивановна"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__wF02P
                  )}
                >
                  {
                    "12.03.1994\r\n\r\nПомощник прокурора Советского района Минска. юрист 3 класса\r\n\r\nВыступала гособвинителем по делу о клевете в отношении Лукашенко. Минчанина Игоря Ухалюка приговорили...."
                  }
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"group49"}
              data-plasmic-override={overrides.group49}
              className={classNames(defaultcss.all, sty.group49)}
            >
              <div
                data-plasmic-name={"group50"}
                data-plasmic-override={overrides.group50}
                className={classNames(defaultcss.all, sty.group50)}
              >
                <div
                  data-plasmic-name={"group28"}
                  data-plasmic-override={overrides.group28}
                  className={classNames(defaultcss.all, sty.group28)}
                >
                  <div
                    data-plasmic-name={"image31"}
                    data-plasmic-override={overrides.image31}
                    className={classNames(defaultcss.all, sty.image31)}
                  />
                </div>

                <Rectangle20Icon
                  className={classNames(defaultcss.all, sty.svg__vI4W)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__mQvOf
                  )}
                >
                  {"Милиционер"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__bB8Qq
                  )}
                >
                  {"Бородич Лина Ивановна"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__kbPgc
                  )}
                >
                  {
                    "12.03.1994\r\n\r\nПомощник прокурора Советского района Минска. юрист 3 класса\r\n\r\nВыступала гособвинителем по делу о клевете в отношении Лукашенко. Минчанина Игоря Ухалюка приговорили...."
                  }
                </div>
              </div>
            </div>

            <Line16Icon
              className={classNames(defaultcss.all, sty.svg__kqbEd)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__dPiy
              )}
            >
              {"Бордич"}
            </div>

            <div
              data-plasmic-name={"group29"}
              data-plasmic-override={overrides.group29}
              className={classNames(defaultcss.all, sty.group29)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__sT7Fh
                )}
              >
                {"Загрузить больше"}
              </div>

              <Arrow2Icon
                className={classNames(defaultcss.all, sty.svg__iMkj)}
                role={"img"}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "findResultPageDesktop",
    "photo202108171656131",
    "group8",
    "group1",
    "verify1",
    "rectangle3",
    "group10",
    "profile",
    "group24",
    "image27",
    "profile2",
    "group25",
    "image28",
    "profile3",
    "group23",
    "image26",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18",
    "group46",
    "group45",
    "group26",
    "image29",
    "group47",
    "group48",
    "group27",
    "image30",
    "group49",
    "group50",
    "group28",
    "image31",
    "group29"
  ],

  findResultPageDesktop: [
    "findResultPageDesktop",
    "photo202108171656131",
    "group8",
    "group1",
    "verify1",
    "rectangle3",
    "group10",
    "profile",
    "group24",
    "image27",
    "profile2",
    "group25",
    "image28",
    "profile3",
    "group23",
    "image26",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18",
    "group46",
    "group45",
    "group26",
    "image29",
    "group47",
    "group48",
    "group27",
    "image30",
    "group49",
    "group50",
    "group28",
    "image31",
    "group29"
  ],

  photo202108171656131: ["photo202108171656131"],
  group8: ["group8"],
  group1: ["group1", "verify1", "rectangle3"],
  verify1: ["verify1"],
  rectangle3: ["rectangle3"],
  group10: ["group10"],
  profile: ["profile", "group24", "image27"],
  group24: ["group24", "image27"],
  image27: ["image27"],
  profile2: ["profile2", "group25", "image28"],
  group25: ["group25", "image28"],
  image28: ["image28"],
  profile3: ["profile3", "group23", "image26"],
  group23: ["group23", "image26"],
  image26: ["image26"],
  union1: ["union1"],
  union8: ["union8"],
  union3: ["union3"],
  union9: ["union9"],
  union5: ["union5"],
  union10: ["union10"],
  union2: ["union2"],
  union11: ["union11"],
  union4: ["union4"],
  union12: ["union12"],
  union6: ["union6"],
  union13: ["union13"],
  union7: ["union7"],
  union14: ["union14"],
  rectangle21: ["rectangle21"],
  group20: ["group20", "rectangle18"],
  rectangle18: ["rectangle18"],
  group46: ["group46", "group45", "group26", "image29"],
  group45: ["group45", "group26", "image29"],
  group26: ["group26", "image29"],
  image29: ["image29"],
  group47: ["group47", "group48", "group27", "image30"],
  group48: ["group48", "group27", "image30"],
  group27: ["group27", "image30"],
  image30: ["image30"],
  group49: ["group49", "group50", "group28", "image31"],
  group50: ["group50", "group28", "image31"],
  group28: ["group28", "image31"],
  image31: ["image31"],
  group29: ["group29"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFindResults__ArgProps,
      internalVariantPropNames: PlasmicFindResults__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicFindResults__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFindResults";
  } else {
    func.displayName = `PlasmicFindResults.${nodeName}`;
  }
  return func;
}

export const PlasmicFindResults = Object.assign(
  // Top-level PlasmicFindResults renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    findResultPageDesktop: makeNodeComponent("findResultPageDesktop"),
    photo202108171656131: makeNodeComponent("photo202108171656131"),
    group8: makeNodeComponent("group8"),
    group1: makeNodeComponent("group1"),
    verify1: makeNodeComponent("verify1"),
    rectangle3: makeNodeComponent("rectangle3"),
    group10: makeNodeComponent("group10"),
    profile: makeNodeComponent("profile"),
    group24: makeNodeComponent("group24"),
    image27: makeNodeComponent("image27"),
    profile2: makeNodeComponent("profile2"),
    group25: makeNodeComponent("group25"),
    image28: makeNodeComponent("image28"),
    profile3: makeNodeComponent("profile3"),
    group23: makeNodeComponent("group23"),
    image26: makeNodeComponent("image26"),
    union1: makeNodeComponent("union1"),
    union8: makeNodeComponent("union8"),
    union3: makeNodeComponent("union3"),
    union9: makeNodeComponent("union9"),
    union5: makeNodeComponent("union5"),
    union10: makeNodeComponent("union10"),
    union2: makeNodeComponent("union2"),
    union11: makeNodeComponent("union11"),
    union4: makeNodeComponent("union4"),
    union12: makeNodeComponent("union12"),
    union6: makeNodeComponent("union6"),
    union13: makeNodeComponent("union13"),
    union7: makeNodeComponent("union7"),
    union14: makeNodeComponent("union14"),
    rectangle21: makeNodeComponent("rectangle21"),
    group20: makeNodeComponent("group20"),
    rectangle18: makeNodeComponent("rectangle18"),
    group46: makeNodeComponent("group46"),
    group45: makeNodeComponent("group45"),
    group26: makeNodeComponent("group26"),
    image29: makeNodeComponent("image29"),
    group47: makeNodeComponent("group47"),
    group48: makeNodeComponent("group48"),
    group27: makeNodeComponent("group27"),
    image30: makeNodeComponent("image30"),
    group49: makeNodeComponent("group49"),
    group50: makeNodeComponent("group50"),
    group28: makeNodeComponent("group28"),
    image31: makeNodeComponent("image31"),
    group29: makeNodeComponent("group29"),
    // Metadata about props expected for PlasmicFindResults
    internalVariantProps: PlasmicFindResults__VariantProps,
    internalArgProps: PlasmicFindResults__ArgProps
  }
);

export default PlasmicFindResults;
/* prettier-ignore-end */
