// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iw4cFYZtgxW7YvDehgMC47
// Component: u9fUcvMLUTC
import * as React from "react";
import Head from "next/head";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_project_web.module.css"; // plasmic-import: iw4cFYZtgxW7YvDehgMC47/projectcss
import * as sty from "./PlasmicMapPage.module.css"; // plasmic-import: u9fUcvMLUTC/css
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: RWzvUW32AX/icon
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: 4NZJoj-fIt/icon
import Line4Icon from "./icons/PlasmicIcon__Line4"; // plasmic-import: vY-U8OLG9IH/icon
import Line11Icon from "./icons/PlasmicIcon__Line11"; // plasmic-import: 1fCRbA0GDb/icon
import Line3Icon from "./icons/PlasmicIcon__Line3"; // plasmic-import: LvtI6YAzhDC/icon
import Line8Icon from "./icons/PlasmicIcon__Line8"; // plasmic-import: OWLbkpHPcZo/icon
import Polygon1Icon from "./icons/PlasmicIcon__Polygon1"; // plasmic-import: QaRBHQulwLs/icon
import Rectangle20Icon from "./icons/PlasmicIcon__Rectangle20"; // plasmic-import: zWq4rB1ZbJo/icon
import Line12Icon from "./icons/PlasmicIcon__Line12"; // plasmic-import: yZORk1xeNod/icon
import Rectangle21Icon from "./icons/PlasmicIcon__Rectangle21"; // plasmic-import: YlCQkwNXRUO/icon
import Arrow3Icon from "./icons/PlasmicIcon__Arrow3"; // plasmic-import: zKLUNirn3XN/icon

export const PlasmicMapPage__VariantProps = new Array();

export const PlasmicMapPage__ArgProps = new Array();

function PlasmicMapPage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"mapPageDesktop"}
            data-plasmic-override={overrides.mapPageDesktop}
            className={classNames(defaultcss.all, sty.mapPageDesktop)}
          >
            {false ? (
              <Line5Icon
                className={classNames(defaultcss.all, sty.svg__rUf2B)}
                role={"img"}
              />
            ) : null}

            <div
              data-plasmic-name={"photo202108171656131"}
              data-plasmic-override={overrides.photo202108171656131}
              className={classNames(defaultcss.all, sty.photo202108171656131)}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__qguwd)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__c5URi)}
              role={"img"}
            />

            <Line4Icon
              className={classNames(defaultcss.all, sty.svg__vLe06)}
              role={"img"}
            />

            <Line11Icon
              className={classNames(defaultcss.all, sty.svg__s6XMt)}
              role={"img"}
            />

            <Line3Icon
              className={classNames(defaultcss.all, sty.svg__juZrs)}
              role={"img"}
            />

            <Line8Icon
              data-plasmic-name={"underlinePartners"}
              data-plasmic-override={overrides.underlinePartners}
              className={classNames(defaultcss.all, sty.underlinePartners)}
              role={"img"}
            />

            <div
              data-plasmic-name={"group8"}
              data-plasmic-override={overrides.group8}
              className={classNames(defaultcss.all, sty.group8)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__i7Ga0
                )}
              >
                {"О ПРОЕКТЕ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__cqlW6
                )}
              >
                {"ПОДДЕРЖАТЬ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__royAx
                )}
              >
                {"ЛЮДИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__ge8Bq
                )}
              >
                {"НОВОСТИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___6GsUj
                )}
              >
                {"КАРТА ПРЕСТУПНИКОВ"}
              </div>
            </div>

            <div
              data-plasmic-name={"group1"}
              data-plasmic-override={overrides.group1}
              className={classNames(defaultcss.all, sty.group1)}
            >
              <div
                data-plasmic-name={"verify1"}
                data-plasmic-override={overrides.verify1}
                className={classNames(defaultcss.all, sty.verify1)}
              />

              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(defaultcss.all, sty.rectangle3)}
              />
            </div>

            <div
              data-plasmic-name={"group10"}
              data-plasmic-override={overrides.group10}
              className={classNames(defaultcss.all, sty.group10)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__rt6Kv
                )}
              >
                {"Выбрать регион"}
              </div>

              <Polygon1Icon
                className={classNames(defaultcss.all, sty.svg__wkAo9)}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"mapHeader"}
              data-plasmic-override={overrides.mapHeader}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.mapHeader
              )}
            >
              {"КАРТА ПРЕСТУПНИКОВ"}
            </div>

            <div
              data-plasmic-name={"pertnersHeader"}
              data-plasmic-override={overrides.pertnersHeader}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.pertnersHeader
              )}
            >
              {"НАШИ ПАРТНЕРЫ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__x7KHf
              )}
            >
              {"ИХ ЧАСТО ИЩУТ"}
            </div>

            <div
              data-plasmic-name={"profile"}
              data-plasmic-override={overrides.profile}
              className={classNames(defaultcss.all, sty.profile)}
            >
              <div
                data-plasmic-name={"group24"}
                data-plasmic-override={overrides.group24}
                className={classNames(defaultcss.all, sty.group24)}
              >
                <div
                  data-plasmic-name={"person"}
                  data-plasmic-override={overrides.person}
                  className={classNames(defaultcss.all, sty.person)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg___2Sncu)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__uni8W
                )}
              >
                {"Милиционер"}
              </div>

              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile2"}
              data-plasmic-override={overrides.profile2}
              className={classNames(defaultcss.all, sty.profile2)}
            >
              <div
                data-plasmic-name={"group25"}
                data-plasmic-override={overrides.group25}
                className={classNames(defaultcss.all, sty.group25)}
              >
                <div
                  data-plasmic-name={"person2"}
                  data-plasmic-override={overrides.person2}
                  className={classNames(defaultcss.all, sty.person2)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg___1Ws4D)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__rSQmP
                )}
              >
                {"Милиционер"}
              </div>

              <div
                data-plasmic-name={"text2"}
                data-plasmic-override={overrides.text2}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text2
                )}
              >
                {"Терехов Александр Александрович"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile3"}
              data-plasmic-override={overrides.profile3}
              className={classNames(defaultcss.all, sty.profile3)}
            >
              <div
                data-plasmic-name={"group23"}
                data-plasmic-override={overrides.group23}
                className={classNames(defaultcss.all, sty.group23)}
              >
                <div
                  data-plasmic-name={"person3"}
                  data-plasmic-override={overrides.person3}
                  className={classNames(defaultcss.all, sty.person3)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__zwRux)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__c5WjI
                )}
              >
                {"Милиционер"}
              </div>

              <div
                data-plasmic-name={"text3"}
                data-plasmic-override={overrides.text3}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text3
                )}
              >
                {"Занько Дмитрий Александрович"}
              </div>
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__biiRb
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/ видео подтверждения и тра-тра-та наш бот @botbotbot"
              }
            </div>

            <div
              data-plasmic-name={"union1"}
              data-plasmic-override={overrides.union1}
              className={classNames(defaultcss.all, sty.union1)}
            />

            <div
              data-plasmic-name={"union8"}
              data-plasmic-override={overrides.union8}
              className={classNames(defaultcss.all, sty.union8)}
            />

            <div
              data-plasmic-name={"union3"}
              data-plasmic-override={overrides.union3}
              className={classNames(defaultcss.all, sty.union3)}
            />

            <div
              data-plasmic-name={"union9"}
              data-plasmic-override={overrides.union9}
              className={classNames(defaultcss.all, sty.union9)}
            />

            <div
              data-plasmic-name={"union5"}
              data-plasmic-override={overrides.union5}
              className={classNames(defaultcss.all, sty.union5)}
            />

            <div
              data-plasmic-name={"union10"}
              data-plasmic-override={overrides.union10}
              className={classNames(defaultcss.all, sty.union10)}
            />

            <div
              data-plasmic-name={"union2"}
              data-plasmic-override={overrides.union2}
              className={classNames(defaultcss.all, sty.union2)}
            />

            <div
              data-plasmic-name={"union11"}
              data-plasmic-override={overrides.union11}
              className={classNames(defaultcss.all, sty.union11)}
            />

            <div
              data-plasmic-name={"union4"}
              data-plasmic-override={overrides.union4}
              className={classNames(defaultcss.all, sty.union4)}
            />

            <div
              data-plasmic-name={"union12"}
              data-plasmic-override={overrides.union12}
              className={classNames(defaultcss.all, sty.union12)}
            />

            <div
              data-plasmic-name={"union6"}
              data-plasmic-override={overrides.union6}
              className={classNames(defaultcss.all, sty.union6)}
            />

            <div
              data-plasmic-name={"union13"}
              data-plasmic-override={overrides.union13}
              className={classNames(defaultcss.all, sty.union13)}
            />

            <div
              data-plasmic-name={"union7"}
              data-plasmic-override={overrides.union7}
              className={classNames(defaultcss.all, sty.union7)}
            />

            <div
              data-plasmic-name={"union14"}
              data-plasmic-override={overrides.union14}
              className={classNames(defaultcss.all, sty.union14)}
            />

            <div
              data-plasmic-name={"rectangle21"}
              data-plasmic-override={overrides.rectangle21}
              className={classNames(defaultcss.all, sty.rectangle21)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox___59Q58
              )}
            >
              {
                "Публикуемые личные данные получены из открытых источников методом социальной инженерии или же непосредственно от читателей. Данные публикуются исключительно с целью упрощения последующего расследования преступлений. \n\nКоманда чкб не призывает к насилию. выступает против любого вида дискриминации и порицает разжигание социальной вражды."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__xk4Jg
              )}
            >
              {"Связаться с нами через бота"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__wmfeR
              )}
            >
              {"Ошибка в тексте?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__ijXRk
              )}
            >
              {"ЧЕРНАЯ КНИГА БЕЛАРУСИ"}
            </div>

            <div
              data-plasmic-name={"group20"}
              data-plasmic-override={overrides.group20}
              className={classNames(defaultcss.all, sty.group20)}
            >
              <div
                data-plasmic-name={"rectangle18"}
                data-plasmic-override={overrides.rectangle18}
                className={classNames(defaultcss.all, sty.rectangle18)}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox___4RK0M
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/"
              }
            </div>

            <div
              data-plasmic-name={"map"}
              data-plasmic-override={overrides.map}
              className={classNames(defaultcss.all, sty.map)}
            />

            <div
              data-plasmic-name={"placeholder11"}
              data-plasmic-override={overrides.placeholder11}
              className={classNames(defaultcss.all, sty.placeholder11)}
            />

            <div
              data-plasmic-name={"placeholder12"}
              data-plasmic-override={overrides.placeholder12}
              className={classNames(defaultcss.all, sty.placeholder12)}
            />

            <div
              data-plasmic-name={"placeholder13"}
              data-plasmic-override={overrides.placeholder13}
              className={classNames(defaultcss.all, sty.placeholder13)}
            />

            <div
              data-plasmic-name={"placeholder14"}
              data-plasmic-override={overrides.placeholder14}
              className={classNames(defaultcss.all, sty.placeholder14)}
            />

            <div
              data-plasmic-name={"карточкаНаКарте"}
              data-plasmic-override={overrides.карточкаНаКарте}
              className={classNames(defaultcss.all, sty.карточканакарте)}
            >
              <div
                data-plasmic-name={"rectangle23"}
                data-plasmic-override={overrides.rectangle23}
                className={classNames(defaultcss.all, sty.rectangle23)}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__bOkFc
                )}
              >
                {"Минск, Фрунзенская 101б, 54 - 23"}
              </div>

              <div
                data-plasmic-name={"placeholder15"}
                data-plasmic-override={overrides.placeholder15}
                className={classNames(defaultcss.all, sty.placeholder15)}
              />

              <Line12Icon
                className={classNames(defaultcss.all, sty.svg__v0WzY)}
                role={"img"}
              />

              <div
                data-plasmic-name={"profile4"}
                data-plasmic-override={overrides.profile4}
                className={classNames(defaultcss.all, sty.profile4)}
              >
                <div
                  data-plasmic-name={"group26"}
                  data-plasmic-override={overrides.group26}
                  className={classNames(defaultcss.all, sty.group26)}
                >
                  <div
                    data-plasmic-name={"image29"}
                    data-plasmic-override={overrides.image29}
                    className={classNames(defaultcss.all, sty.image29)}
                  />
                </div>

                <Rectangle21Icon
                  className={classNames(defaultcss.all, sty.svg__hof9Q)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__of7Uo
                  )}
                >
                  {"Милиционер"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__z513J
                  )}
                >
                  {"Бородич Лина Ивановна"}
                </div>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__wEaHc
                )}
              >
                {"Смотреть профиль"}
              </div>
            </div>

            <Arrow3Icon
              className={classNames(defaultcss.all, sty.svg__nLzsX)}
              role={"img"}
            />

            <div
              data-plasmic-name={"image31"}
              data-plasmic-override={overrides.image31}
              className={classNames(defaultcss.all, sty.image31)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "mapPageDesktop",
    "photo202108171656131",
    "underlinePartners",
    "group8",
    "group1",
    "verify1",
    "rectangle3",
    "group10",
    "mapHeader",
    "pertnersHeader",
    "profile",
    "group24",
    "person",
    "text",
    "profile2",
    "group25",
    "person2",
    "text2",
    "profile3",
    "group23",
    "person3",
    "text3",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18",
    "map",
    "placeholder11",
    "placeholder12",
    "placeholder13",
    "placeholder14",
    "карточкаНаКарте",
    "rectangle23",
    "placeholder15",
    "profile4",
    "group26",
    "image29",
    "image31"
  ],

  mapPageDesktop: [
    "mapPageDesktop",
    "photo202108171656131",
    "underlinePartners",
    "group8",
    "group1",
    "verify1",
    "rectangle3",
    "group10",
    "mapHeader",
    "pertnersHeader",
    "profile",
    "group24",
    "person",
    "text",
    "profile2",
    "group25",
    "person2",
    "text2",
    "profile3",
    "group23",
    "person3",
    "text3",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18",
    "map",
    "placeholder11",
    "placeholder12",
    "placeholder13",
    "placeholder14",
    "карточкаНаКарте",
    "rectangle23",
    "placeholder15",
    "profile4",
    "group26",
    "image29",
    "image31"
  ],

  photo202108171656131: ["photo202108171656131"],
  underlinePartners: ["underlinePartners"],
  group8: ["group8"],
  group1: ["group1", "verify1", "rectangle3"],
  verify1: ["verify1"],
  rectangle3: ["rectangle3"],
  group10: ["group10"],
  mapHeader: ["mapHeader"],
  pertnersHeader: ["pertnersHeader"],
  profile: ["profile", "group24", "person", "text"],
  group24: ["group24", "person"],
  person: ["person"],
  text: ["text"],
  profile2: ["profile2", "group25", "person2", "text2"],
  group25: ["group25", "person2"],
  person2: ["person2"],
  text2: ["text2"],
  profile3: ["profile3", "group23", "person3", "text3"],
  group23: ["group23", "person3"],
  person3: ["person3"],
  text3: ["text3"],
  union1: ["union1"],
  union8: ["union8"],
  union3: ["union3"],
  union9: ["union9"],
  union5: ["union5"],
  union10: ["union10"],
  union2: ["union2"],
  union11: ["union11"],
  union4: ["union4"],
  union12: ["union12"],
  union6: ["union6"],
  union13: ["union13"],
  union7: ["union7"],
  union14: ["union14"],
  rectangle21: ["rectangle21"],
  group20: ["group20", "rectangle18"],
  rectangle18: ["rectangle18"],
  map: ["map"],
  placeholder11: ["placeholder11"],
  placeholder12: ["placeholder12"],
  placeholder13: ["placeholder13"],
  placeholder14: ["placeholder14"],
  карточкаНаКарте: [
    "карточкаНаКарте",
    "rectangle23",
    "placeholder15",
    "profile4",
    "group26",
    "image29"
  ],

  rectangle23: ["rectangle23"],
  placeholder15: ["placeholder15"],
  profile4: ["profile4", "group26", "image29"],
  group26: ["group26", "image29"],
  image29: ["image29"],
  image31: ["image31"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMapPage__ArgProps,
      internalVariantPropNames: PlasmicMapPage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicMapPage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMapPage";
  } else {
    func.displayName = `PlasmicMapPage.${nodeName}`;
  }
  return func;
}

export const PlasmicMapPage = Object.assign(
  // Top-level PlasmicMapPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mapPageDesktop: makeNodeComponent("mapPageDesktop"),
    photo202108171656131: makeNodeComponent("photo202108171656131"),
    underlinePartners: makeNodeComponent("underlinePartners"),
    group8: makeNodeComponent("group8"),
    group1: makeNodeComponent("group1"),
    verify1: makeNodeComponent("verify1"),
    rectangle3: makeNodeComponent("rectangle3"),
    group10: makeNodeComponent("group10"),
    mapHeader: makeNodeComponent("mapHeader"),
    pertnersHeader: makeNodeComponent("pertnersHeader"),
    profile: makeNodeComponent("profile"),
    group24: makeNodeComponent("group24"),
    person: makeNodeComponent("person"),
    text: makeNodeComponent("text"),
    profile2: makeNodeComponent("profile2"),
    group25: makeNodeComponent("group25"),
    person2: makeNodeComponent("person2"),
    text2: makeNodeComponent("text2"),
    profile3: makeNodeComponent("profile3"),
    group23: makeNodeComponent("group23"),
    person3: makeNodeComponent("person3"),
    text3: makeNodeComponent("text3"),
    union1: makeNodeComponent("union1"),
    union8: makeNodeComponent("union8"),
    union3: makeNodeComponent("union3"),
    union9: makeNodeComponent("union9"),
    union5: makeNodeComponent("union5"),
    union10: makeNodeComponent("union10"),
    union2: makeNodeComponent("union2"),
    union11: makeNodeComponent("union11"),
    union4: makeNodeComponent("union4"),
    union12: makeNodeComponent("union12"),
    union6: makeNodeComponent("union6"),
    union13: makeNodeComponent("union13"),
    union7: makeNodeComponent("union7"),
    union14: makeNodeComponent("union14"),
    rectangle21: makeNodeComponent("rectangle21"),
    group20: makeNodeComponent("group20"),
    rectangle18: makeNodeComponent("rectangle18"),
    map: makeNodeComponent("map"),
    placeholder11: makeNodeComponent("placeholder11"),
    placeholder12: makeNodeComponent("placeholder12"),
    placeholder13: makeNodeComponent("placeholder13"),
    placeholder14: makeNodeComponent("placeholder14"),
    карточкаНаКарте: makeNodeComponent("карточкаНаКарте"),
    rectangle23: makeNodeComponent("rectangle23"),
    placeholder15: makeNodeComponent("placeholder15"),
    profile4: makeNodeComponent("profile4"),
    group26: makeNodeComponent("group26"),
    image29: makeNodeComponent("image29"),
    image31: makeNodeComponent("image31"),
    // Metadata about props expected for PlasmicMapPage
    internalVariantProps: PlasmicMapPage__VariantProps,
    internalArgProps: PlasmicMapPage__ArgProps
  }
);

export default PlasmicMapPage;
/* prettier-ignore-end */
