// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iw4cFYZtgxW7YvDehgMC47
// Component: X7evdGKvz-t
import * as React from "react";
import Head from "next/head";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_project_web.module.css"; // plasmic-import: iw4cFYZtgxW7YvDehgMC47/projectcss
import * as sty from "./PlasmicDonate.module.css"; // plasmic-import: X7evdGKvz-t/css
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: 4NZJoj-fIt/icon
import Line4Icon from "./icons/PlasmicIcon__Line4"; // plasmic-import: vY-U8OLG9IH/icon
import Line18Icon from "./icons/PlasmicIcon__Line18"; // plasmic-import: jBoPPohdDt/icon
import Line8Icon from "./icons/PlasmicIcon__Line8"; // plasmic-import: OWLbkpHPcZo/icon
import Polygon1Icon from "./icons/PlasmicIcon__Polygon1"; // plasmic-import: QaRBHQulwLs/icon
import Rectangle20Icon from "./icons/PlasmicIcon__Rectangle20"; // plasmic-import: zWq4rB1ZbJo/icon
import Line19Icon from "./icons/PlasmicIcon__Line19"; // plasmic-import: _ldKxRNK1ul/icon

export const PlasmicDonate__VariantProps = new Array();

export const PlasmicDonate__ArgProps = new Array();

function PlasmicDonate__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"donatePageDesktop"}
            data-plasmic-override={overrides.donatePageDesktop}
            className={classNames(defaultcss.all, sty.donatePageDesktop)}
          >
            <div
              data-plasmic-name={"photo202108171656131"}
              data-plasmic-override={overrides.photo202108171656131}
              className={classNames(defaultcss.all, sty.photo202108171656131)}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg___1N1VQ)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__h8Mwq)}
              role={"img"}
            />

            <Line4Icon
              className={classNames(defaultcss.all, sty.svg__jMo60)}
              role={"img"}
            />

            <Line18Icon
              className={classNames(defaultcss.all, sty.svg__olls8)}
              role={"img"}
            />

            <Line8Icon
              className={classNames(defaultcss.all, sty.svg__fnIvP)}
              role={"img"}
            />

            <div
              data-plasmic-name={"group8"}
              data-plasmic-override={overrides.group8}
              className={classNames(defaultcss.all, sty.group8)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__eHurU
                )}
              >
                {"О ПРОЕКТЕ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__kHYjg
                )}
              >
                {"ПОДДЕРЖАТЬ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__d5AuL
                )}
              >
                {"ЛЮДИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__gdgym
                )}
              >
                {"НОВОСТИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___39Aiu
                )}
              >
                {"КАРТА ПРЕСТУПНИКОВ"}
              </div>
            </div>

            <div
              data-plasmic-name={"group1"}
              data-plasmic-override={overrides.group1}
              className={classNames(defaultcss.all, sty.group1)}
            >
              <div
                data-plasmic-name={"verify1"}
                data-plasmic-override={overrides.verify1}
                className={classNames(defaultcss.all, sty.verify1)}
              />

              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(defaultcss.all, sty.rectangle3)}
              />
            </div>

            <div
              data-plasmic-name={"group10"}
              data-plasmic-override={overrides.group10}
              className={classNames(defaultcss.all, sty.group10)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__ey3Mq
                )}
              >
                {"Выбрать регион"}
              </div>

              <Polygon1Icon
                className={classNames(defaultcss.all, sty.svg___0YVgK)}
                role={"img"}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__aCyU9
              )}
            >
              {"ПОДДЕРЖАТЬ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__qny6X
              )}
            >
              {"НАШИ ПАРТНЕРЫ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__gSaHv
              )}
            >
              {"ИХ ЧАСТО ИЩУТ"}
            </div>

            <div
              data-plasmic-name={"profile"}
              data-plasmic-override={overrides.profile}
              className={classNames(defaultcss.all, sty.profile)}
            >
              <div
                data-plasmic-name={"group24"}
                data-plasmic-override={overrides.group24}
                className={classNames(defaultcss.all, sty.group24)}
              >
                <div
                  data-plasmic-name={"image27"}
                  data-plasmic-override={overrides.image27}
                  className={classNames(defaultcss.all, sty.image27)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg___92Pwp)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__zBen
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__k76MA
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile2"}
              data-plasmic-override={overrides.profile2}
              className={classNames(defaultcss.all, sty.profile2)}
            >
              <div
                data-plasmic-name={"group25"}
                data-plasmic-override={overrides.group25}
                className={classNames(defaultcss.all, sty.group25)}
              >
                <div
                  data-plasmic-name={"image28"}
                  data-plasmic-override={overrides.image28}
                  className={classNames(defaultcss.all, sty.image28)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__vNfoF)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__srGki
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___9NNf
                )}
              >
                {"Терехов Александр Александрович"}
              </div>
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__snjtf
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/ видео подтверждения и тра-тра-та наш бот @botbotbot"
              }
            </div>

            <div
              data-plasmic-name={"union1"}
              data-plasmic-override={overrides.union1}
              className={classNames(defaultcss.all, sty.union1)}
            />

            <div
              data-plasmic-name={"union8"}
              data-plasmic-override={overrides.union8}
              className={classNames(defaultcss.all, sty.union8)}
            />

            <div
              data-plasmic-name={"union3"}
              data-plasmic-override={overrides.union3}
              className={classNames(defaultcss.all, sty.union3)}
            />

            <div
              data-plasmic-name={"union9"}
              data-plasmic-override={overrides.union9}
              className={classNames(defaultcss.all, sty.union9)}
            />

            <div
              data-plasmic-name={"union5"}
              data-plasmic-override={overrides.union5}
              className={classNames(defaultcss.all, sty.union5)}
            />

            <div
              data-plasmic-name={"union10"}
              data-plasmic-override={overrides.union10}
              className={classNames(defaultcss.all, sty.union10)}
            />

            <div
              data-plasmic-name={"union2"}
              data-plasmic-override={overrides.union2}
              className={classNames(defaultcss.all, sty.union2)}
            />

            <div
              data-plasmic-name={"union11"}
              data-plasmic-override={overrides.union11}
              className={classNames(defaultcss.all, sty.union11)}
            />

            <div
              data-plasmic-name={"union4"}
              data-plasmic-override={overrides.union4}
              className={classNames(defaultcss.all, sty.union4)}
            />

            <div
              data-plasmic-name={"union12"}
              data-plasmic-override={overrides.union12}
              className={classNames(defaultcss.all, sty.union12)}
            />

            <div
              data-plasmic-name={"union6"}
              data-plasmic-override={overrides.union6}
              className={classNames(defaultcss.all, sty.union6)}
            />

            <div
              data-plasmic-name={"union13"}
              data-plasmic-override={overrides.union13}
              className={classNames(defaultcss.all, sty.union13)}
            />

            <div
              data-plasmic-name={"union7"}
              data-plasmic-override={overrides.union7}
              className={classNames(defaultcss.all, sty.union7)}
            />

            <div
              data-plasmic-name={"union14"}
              data-plasmic-override={overrides.union14}
              className={classNames(defaultcss.all, sty.union14)}
            />

            <div
              data-plasmic-name={"rectangle21"}
              data-plasmic-override={overrides.rectangle21}
              className={classNames(defaultcss.all, sty.rectangle21)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox___1TRAe
              )}
            >
              {
                "Публикуемые личные данные получены из открытых источников методом социальной инженерии или же непосредственно от читателей. Данные публикуются исключительно с целью упрощения последующего расследования преступлений. \n\nКоманда чкб не призывает к насилию. выступает против любого вида дискриминации и порицает разжигание социальной вражды."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__b9H3
              )}
            >
              {"Связаться с нами через бота"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__yYBgB
              )}
            >
              {"Ошибка в тексте?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox___22Z7J
              )}
            >
              {"ЧЕРНАЯ КНИГА БЕЛАРУСИ"}
            </div>

            <div
              data-plasmic-name={"group20"}
              data-plasmic-override={overrides.group20}
              className={classNames(defaultcss.all, sty.group20)}
            >
              <div
                data-plasmic-name={"rectangle18"}
                data-plasmic-override={overrides.rectangle18}
                className={classNames(defaultcss.all, sty.rectangle18)}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__bG5Cy
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/"
              }
            </div>

            <div
              data-plasmic-name={
                "значимостьЭтихПроблемНастолькоОчевиднаЧтоДальнейшееРазвитиеРазличныхФормДеятельностиОбеспечиваетШирокомуКругуСпециалистовУчастиеВФормированииНовыхПредложенийРавнымОбразомРамкиИМестоОбученияКадровВлечетЗаСобойПроцессВнедренияИМодернизацииСистемыОбученияКадровСоответствуетНасущнымПотребностям"
              }
              data-plasmic-override={
                overrides.значимостьЭтихПроблемНастолькоОчевиднаЧтоДальнейшееРазвитиеРазличныхФормДеятельностиОбеспечиваетШирокомуКругуСпециалистовУчастиеВФормированииНовыхПредложенийРавнымОбразомРамкиИМестоОбученияКадровВлечетЗаСобойПроцессВнедренияИМодернизацииСистемыОбученияКадровСоответствуетНасущнымПотребностям
              }
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.значимостьэтихпроблемнастолькоочевидначтодальнейшееразвитиеразличныхформдеятельностиобеспечиваетширокомукругуспециалистовучастиевформированииновыхпредложенийравнымобразомрамкииместообучениякадроввлечетзасобойпроцессвнедренияимодернизациисистемыобучениякадровсоответствуетнасущнымпотребностям
              )}
            >
              {
                "Значимость этих проблем настолько очевидна, что дальнейшее развитие различных форм деятельности обеспечивает широкому кругу (специалистов) участие в формировании новых предложений. \n\nРавным образом рамки и место обучения кадров влечет за собой процесс внедрения и модернизации системы обучения кадров, соответствует насущным потребностям. "
              }
            </div>

            <Line19Icon
              className={classNames(defaultcss.all, sty.svg__edLlV)}
              role={"img"}
            />

            <div
              data-plasmic-name={"image32"}
              data-plasmic-override={overrides.image32}
              className={classNames(defaultcss.all, sty.image32)}
            />

            <div
              data-plasmic-name={"image34"}
              data-plasmic-override={overrides.image34}
              className={classNames(defaultcss.all, sty.image34)}
            />

            <div
              data-plasmic-name={"image33"}
              data-plasmic-override={overrides.image33}
              className={classNames(defaultcss.all, sty.image33)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "donatePageDesktop",
    "photo202108171656131",
    "group8",
    "group1",
    "verify1",
    "rectangle3",
    "group10",
    "profile",
    "group24",
    "image27",
    "profile2",
    "group25",
    "image28",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18",
    "значимостьЭтихПроблемНастолькоОчевиднаЧтоДальнейшееРазвитиеРазличныхФормДеятельностиОбеспечиваетШирокомуКругуСпециалистовУчастиеВФормированииНовыхПредложенийРавнымОбразомРамкиИМестоОбученияКадровВлечетЗаСобойПроцессВнедренияИМодернизацииСистемыОбученияКадровСоответствуетНасущнымПотребностям",
    "image32",
    "image34",
    "image33"
  ],

  donatePageDesktop: [
    "donatePageDesktop",
    "photo202108171656131",
    "group8",
    "group1",
    "verify1",
    "rectangle3",
    "group10",
    "profile",
    "group24",
    "image27",
    "profile2",
    "group25",
    "image28",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18",
    "значимостьЭтихПроблемНастолькоОчевиднаЧтоДальнейшееРазвитиеРазличныхФормДеятельностиОбеспечиваетШирокомуКругуСпециалистовУчастиеВФормированииНовыхПредложенийРавнымОбразомРамкиИМестоОбученияКадровВлечетЗаСобойПроцессВнедренияИМодернизацииСистемыОбученияКадровСоответствуетНасущнымПотребностям",
    "image32",
    "image34",
    "image33"
  ],

  photo202108171656131: ["photo202108171656131"],
  group8: ["group8"],
  group1: ["group1", "verify1", "rectangle3"],
  verify1: ["verify1"],
  rectangle3: ["rectangle3"],
  group10: ["group10"],
  profile: ["profile", "group24", "image27"],
  group24: ["group24", "image27"],
  image27: ["image27"],
  profile2: ["profile2", "group25", "image28"],
  group25: ["group25", "image28"],
  image28: ["image28"],
  union1: ["union1"],
  union8: ["union8"],
  union3: ["union3"],
  union9: ["union9"],
  union5: ["union5"],
  union10: ["union10"],
  union2: ["union2"],
  union11: ["union11"],
  union4: ["union4"],
  union12: ["union12"],
  union6: ["union6"],
  union13: ["union13"],
  union7: ["union7"],
  union14: ["union14"],
  rectangle21: ["rectangle21"],
  group20: ["group20", "rectangle18"],
  rectangle18: ["rectangle18"],
  значимостьЭтихПроблемНастолькоОчевиднаЧтоДальнейшееРазвитиеРазличныхФормДеятельностиОбеспечиваетШирокомуКругуСпециалистовУчастиеВФормированииНовыхПредложенийРавнымОбразомРамкиИМестоОбученияКадровВлечетЗаСобойПроцессВнедренияИМодернизацииСистемыОбученияКадровСоответствуетНасущнымПотребностям:
    [
      "значимостьЭтихПроблемНастолькоОчевиднаЧтоДальнейшееРазвитиеРазличныхФормДеятельностиОбеспечиваетШирокомуКругуСпециалистовУчастиеВФормированииНовыхПредложенийРавнымОбразомРамкиИМестоОбученияКадровВлечетЗаСобойПроцессВнедренияИМодернизацииСистемыОбученияКадровСоответствуетНасущнымПотребностям"
    ],

  image32: ["image32"],
  image34: ["image34"],
  image33: ["image33"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicDonate__ArgProps,
      internalVariantPropNames: PlasmicDonate__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicDonate__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDonate";
  } else {
    func.displayName = `PlasmicDonate.${nodeName}`;
  }
  return func;
}

export const PlasmicDonate = Object.assign(
  // Top-level PlasmicDonate renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    donatePageDesktop: makeNodeComponent("donatePageDesktop"),
    photo202108171656131: makeNodeComponent("photo202108171656131"),
    group8: makeNodeComponent("group8"),
    group1: makeNodeComponent("group1"),
    verify1: makeNodeComponent("verify1"),
    rectangle3: makeNodeComponent("rectangle3"),
    group10: makeNodeComponent("group10"),
    profile: makeNodeComponent("profile"),
    group24: makeNodeComponent("group24"),
    image27: makeNodeComponent("image27"),
    profile2: makeNodeComponent("profile2"),
    group25: makeNodeComponent("group25"),
    image28: makeNodeComponent("image28"),
    union1: makeNodeComponent("union1"),
    union8: makeNodeComponent("union8"),
    union3: makeNodeComponent("union3"),
    union9: makeNodeComponent("union9"),
    union5: makeNodeComponent("union5"),
    union10: makeNodeComponent("union10"),
    union2: makeNodeComponent("union2"),
    union11: makeNodeComponent("union11"),
    union4: makeNodeComponent("union4"),
    union12: makeNodeComponent("union12"),
    union6: makeNodeComponent("union6"),
    union13: makeNodeComponent("union13"),
    union7: makeNodeComponent("union7"),
    union14: makeNodeComponent("union14"),
    rectangle21: makeNodeComponent("rectangle21"),
    group20: makeNodeComponent("group20"),
    rectangle18: makeNodeComponent("rectangle18"),
    значимостьЭтихПроблемНастолькоОчевиднаЧтоДальнейшееРазвитиеРазличныхФормДеятельностиОбеспечиваетШирокомуКругуСпециалистовУчастиеВФормированииНовыхПредложенийРавнымОбразомРамкиИМестоОбученияКадровВлечетЗаСобойПроцессВнедренияИМодернизацииСистемыОбученияКадровСоответствуетНасущнымПотребностям:
      makeNodeComponent(
        "значимостьЭтихПроблемНастолькоОчевиднаЧтоДальнейшееРазвитиеРазличныхФормДеятельностиОбеспечиваетШирокомуКругуСпециалистовУчастиеВФормированииНовыхПредложенийРавнымОбразомРамкиИМестоОбученияКадровВлечетЗаСобойПроцессВнедренияИМодернизацииСистемыОбученияКадровСоответствуетНасущнымПотребностям"
      ),

    image32: makeNodeComponent("image32"),
    image34: makeNodeComponent("image34"),
    image33: makeNodeComponent("image33"),
    // Metadata about props expected for PlasmicDonate
    internalVariantProps: PlasmicDonate__VariantProps,
    internalArgProps: PlasmicDonate__ArgProps
  }
);

export default PlasmicDonate;
/* prettier-ignore-end */
