// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iw4cFYZtgxW7YvDehgMC47
// Component: E3LOXvkXg3F
import * as React from "react";
import Head from "next/head";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_project_web.module.css"; // plasmic-import: iw4cFYZtgxW7YvDehgMC47/projectcss
import * as sty from "./PlasmicAboutPage.module.css"; // plasmic-import: E3LOXvkXg3F/css
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: RWzvUW32AX/icon
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: 4NZJoj-fIt/icon
import Line4Icon from "./icons/PlasmicIcon__Line4"; // plasmic-import: vY-U8OLG9IH/icon
import Line10Icon from "./icons/PlasmicIcon__Line10"; // plasmic-import: _NcK4bL9zA/icon
import Line8Icon from "./icons/PlasmicIcon__Line8"; // plasmic-import: OWLbkpHPcZo/icon
import Polygon1Icon from "./icons/PlasmicIcon__Polygon1"; // plasmic-import: QaRBHQulwLs/icon
import Rectangle20Icon from "./icons/PlasmicIcon__Rectangle20"; // plasmic-import: zWq4rB1ZbJo/icon
import Line17Icon from "./icons/PlasmicIcon__Line17"; // plasmic-import: lMxeT0I5eW7/icon

export const PlasmicAboutPage__VariantProps = new Array();

export const PlasmicAboutPage__ArgProps = new Array();

function PlasmicAboutPage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"aboutPageDesktop"}
            data-plasmic-override={overrides.aboutPageDesktop}
            className={classNames(defaultcss.all, sty.aboutPageDesktop)}
          >
            {false ? (
              <Line5Icon
                className={classNames(defaultcss.all, sty.svg__dhQd)}
                role={"img"}
              />
            ) : null}

            <div
              data-plasmic-name={"photo202108171656131"}
              data-plasmic-override={overrides.photo202108171656131}
              className={classNames(defaultcss.all, sty.photo202108171656131)}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__cpZue)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__guTe5)}
              role={"img"}
            />

            <Line4Icon
              className={classNames(defaultcss.all, sty.svg___3ByU)}
              role={"img"}
            />

            <Line10Icon
              className={classNames(defaultcss.all, sty.svg__mmPHs)}
              role={"img"}
            />

            <Line8Icon
              className={classNames(defaultcss.all, sty.svg___2ZXWt)}
              role={"img"}
            />

            <div
              data-plasmic-name={"group8"}
              data-plasmic-override={overrides.group8}
              className={classNames(defaultcss.all, sty.group8)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___6YJcr
                )}
              >
                {"О ПРОЕКТЕ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__geYhU
                )}
              >
                {"ПОДДЕРЖАТЬ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__z9BzS
                )}
              >
                {"ЛЮДИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__n7JFo
                )}
              >
                {"НОВОСТИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__orAx4
                )}
              >
                {"КАРТА ПРЕСТУПНИКОВ"}
              </div>
            </div>

            <div
              data-plasmic-name={"group1"}
              data-plasmic-override={overrides.group1}
              className={classNames(defaultcss.all, sty.group1)}
            >
              <div
                data-plasmic-name={"verify1"}
                data-plasmic-override={overrides.verify1}
                className={classNames(defaultcss.all, sty.verify1)}
              />

              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(defaultcss.all, sty.rectangle3)}
              />
            </div>

            <div
              data-plasmic-name={"group10"}
              data-plasmic-override={overrides.group10}
              className={classNames(defaultcss.all, sty.group10)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__i61Hf
                )}
              >
                {"Выбрать регион"}
              </div>

              <Polygon1Icon
                className={classNames(defaultcss.all, sty.svg__fQuNr)}
                role={"img"}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox___2Lom
              )}
            >
              {"О ПРОЕКТЕ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox___2Qy5R
              )}
            >
              {"НАШИ ПАРТНЕРЫ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__jJwsw
              )}
            >
              {"ИХ ЧАСТО ИЩУТ"}
            </div>

            <div
              data-plasmic-name={"profile"}
              data-plasmic-override={overrides.profile}
              className={classNames(defaultcss.all, sty.profile)}
            >
              <div
                data-plasmic-name={"group24"}
                data-plasmic-override={overrides.group24}
                className={classNames(defaultcss.all, sty.group24)}
              >
                <div
                  data-plasmic-name={"image27"}
                  data-plasmic-override={overrides.image27}
                  className={classNames(defaultcss.all, sty.image27)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__w0LC2)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__r0WMo
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__cr4Hs
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile2"}
              data-plasmic-override={overrides.profile2}
              className={classNames(defaultcss.all, sty.profile2)}
            >
              <div
                data-plasmic-name={"group25"}
                data-plasmic-override={overrides.group25}
                className={classNames(defaultcss.all, sty.group25)}
              >
                <div
                  data-plasmic-name={"image28"}
                  data-plasmic-override={overrides.image28}
                  className={classNames(defaultcss.all, sty.image28)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__xOHgw)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___7Esj8
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__o2Bk8
                )}
              >
                {"Терехов Александр Александрович"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile3"}
              data-plasmic-override={overrides.profile3}
              className={classNames(defaultcss.all, sty.profile3)}
            >
              <div
                data-plasmic-name={"group23"}
                data-plasmic-override={overrides.group23}
                className={classNames(defaultcss.all, sty.group23)}
              >
                <div
                  data-plasmic-name={"image26"}
                  data-plasmic-override={overrides.image26}
                  className={classNames(defaultcss.all, sty.image26)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__xpH19)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__a5TAx
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__lxLQj
                )}
              >
                {"Занько Дмитрий Александрович"}
              </div>
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__iwVEg
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/ видео подтверждения и тра-тра-та наш бот @botbotbot"
              }
            </div>

            <div
              data-plasmic-name={"union1"}
              data-plasmic-override={overrides.union1}
              className={classNames(defaultcss.all, sty.union1)}
            />

            <div
              data-plasmic-name={"union8"}
              data-plasmic-override={overrides.union8}
              className={classNames(defaultcss.all, sty.union8)}
            />

            <div
              data-plasmic-name={"union3"}
              data-plasmic-override={overrides.union3}
              className={classNames(defaultcss.all, sty.union3)}
            />

            <div
              data-plasmic-name={"union9"}
              data-plasmic-override={overrides.union9}
              className={classNames(defaultcss.all, sty.union9)}
            />

            <div
              data-plasmic-name={"union5"}
              data-plasmic-override={overrides.union5}
              className={classNames(defaultcss.all, sty.union5)}
            />

            <div
              data-plasmic-name={"union10"}
              data-plasmic-override={overrides.union10}
              className={classNames(defaultcss.all, sty.union10)}
            />

            <div
              data-plasmic-name={"union2"}
              data-plasmic-override={overrides.union2}
              className={classNames(defaultcss.all, sty.union2)}
            />

            <div
              data-plasmic-name={"union11"}
              data-plasmic-override={overrides.union11}
              className={classNames(defaultcss.all, sty.union11)}
            />

            <div
              data-plasmic-name={"union4"}
              data-plasmic-override={overrides.union4}
              className={classNames(defaultcss.all, sty.union4)}
            />

            <div
              data-plasmic-name={"union12"}
              data-plasmic-override={overrides.union12}
              className={classNames(defaultcss.all, sty.union12)}
            />

            <div
              data-plasmic-name={"union6"}
              data-plasmic-override={overrides.union6}
              className={classNames(defaultcss.all, sty.union6)}
            />

            <div
              data-plasmic-name={"union13"}
              data-plasmic-override={overrides.union13}
              className={classNames(defaultcss.all, sty.union13)}
            />

            <div
              data-plasmic-name={"union7"}
              data-plasmic-override={overrides.union7}
              className={classNames(defaultcss.all, sty.union7)}
            />

            <div
              data-plasmic-name={"union14"}
              data-plasmic-override={overrides.union14}
              className={classNames(defaultcss.all, sty.union14)}
            />

            <div
              data-plasmic-name={"rectangle21"}
              data-plasmic-override={overrides.rectangle21}
              className={classNames(defaultcss.all, sty.rectangle21)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__xAJs
              )}
            >
              {
                "Публикуемые личные данные получены из открытых источников методом социальной инженерии или же непосредственно от читателей. Данные публикуются исключительно с целью упрощения последующего расследования преступлений. \n\nКоманда чкб не призывает к насилию. выступает против любого вида дискриминации и порицает разжигание социальной вражды."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__yKqP
              )}
            >
              {"Связаться с нами через бота"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__qbUN
              )}
            >
              {"Ошибка в тексте?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__a9VPl
              )}
            >
              {"ЧЕРНАЯ КНИГА БЕЛАРУСИ"}
            </div>

            <div
              data-plasmic-name={"group20"}
              data-plasmic-override={overrides.group20}
              className={classNames(defaultcss.all, sty.group20)}
            >
              <div
                data-plasmic-name={"rectangle18"}
                data-plasmic-override={overrides.rectangle18}
                className={classNames(defaultcss.all, sty.rectangle18)}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__nUgQ1
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/"
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox___9MxXn
              )}
            >
              {
                "Значимость этих проблем настолько очевидна, что дальнейшее развитие различных форм деятельности обеспечивает широкому кругу (специалистов) участие в формировании новых предложений. \n\nРавным образом рамки и место обучения кадров влечет за собой процесс внедрения и модернизации системы обучения кадров, соответствует насущным потребностям. \n\nИдейные соображения высшего порядка, а также рамки и место обучения кадров обеспечивает широкому кругу (специалистов) участие в формировании новых предложений. С другой стороны укрепление и развитие структуры обеспечивает участие в формировании систем массового участия. \n\nИдейные соображения высшего порядка, а также начало повседневной работы по формированию позиции позволяет оценить значение модели развития. \n\nЗначимость этих проблем настолько очевидна, что консультация с широким активом играет важную роль в формировании новых предложений. Равным образом постоянный количественный рост и сфера нашей активности играет важную роль в формировании системы обучения кадров, соответствует насущным."
              }
            </div>

            <Line17Icon
              className={classNames(defaultcss.all, sty.svg__brDi2)}
              role={"img"}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "aboutPageDesktop",
    "photo202108171656131",
    "group8",
    "group1",
    "verify1",
    "rectangle3",
    "group10",
    "profile",
    "group24",
    "image27",
    "profile2",
    "group25",
    "image28",
    "profile3",
    "group23",
    "image26",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18"
  ],

  aboutPageDesktop: [
    "aboutPageDesktop",
    "photo202108171656131",
    "group8",
    "group1",
    "verify1",
    "rectangle3",
    "group10",
    "profile",
    "group24",
    "image27",
    "profile2",
    "group25",
    "image28",
    "profile3",
    "group23",
    "image26",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18"
  ],

  photo202108171656131: ["photo202108171656131"],
  group8: ["group8"],
  group1: ["group1", "verify1", "rectangle3"],
  verify1: ["verify1"],
  rectangle3: ["rectangle3"],
  group10: ["group10"],
  profile: ["profile", "group24", "image27"],
  group24: ["group24", "image27"],
  image27: ["image27"],
  profile2: ["profile2", "group25", "image28"],
  group25: ["group25", "image28"],
  image28: ["image28"],
  profile3: ["profile3", "group23", "image26"],
  group23: ["group23", "image26"],
  image26: ["image26"],
  union1: ["union1"],
  union8: ["union8"],
  union3: ["union3"],
  union9: ["union9"],
  union5: ["union5"],
  union10: ["union10"],
  union2: ["union2"],
  union11: ["union11"],
  union4: ["union4"],
  union12: ["union12"],
  union6: ["union6"],
  union13: ["union13"],
  union7: ["union7"],
  union14: ["union14"],
  rectangle21: ["rectangle21"],
  group20: ["group20", "rectangle18"],
  rectangle18: ["rectangle18"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAboutPage__ArgProps,
      internalVariantPropNames: PlasmicAboutPage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicAboutPage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutPage";
  } else {
    func.displayName = `PlasmicAboutPage.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutPage = Object.assign(
  // Top-level PlasmicAboutPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    aboutPageDesktop: makeNodeComponent("aboutPageDesktop"),
    photo202108171656131: makeNodeComponent("photo202108171656131"),
    group8: makeNodeComponent("group8"),
    group1: makeNodeComponent("group1"),
    verify1: makeNodeComponent("verify1"),
    rectangle3: makeNodeComponent("rectangle3"),
    group10: makeNodeComponent("group10"),
    profile: makeNodeComponent("profile"),
    group24: makeNodeComponent("group24"),
    image27: makeNodeComponent("image27"),
    profile2: makeNodeComponent("profile2"),
    group25: makeNodeComponent("group25"),
    image28: makeNodeComponent("image28"),
    profile3: makeNodeComponent("profile3"),
    group23: makeNodeComponent("group23"),
    image26: makeNodeComponent("image26"),
    union1: makeNodeComponent("union1"),
    union8: makeNodeComponent("union8"),
    union3: makeNodeComponent("union3"),
    union9: makeNodeComponent("union9"),
    union5: makeNodeComponent("union5"),
    union10: makeNodeComponent("union10"),
    union2: makeNodeComponent("union2"),
    union11: makeNodeComponent("union11"),
    union4: makeNodeComponent("union4"),
    union12: makeNodeComponent("union12"),
    union6: makeNodeComponent("union6"),
    union13: makeNodeComponent("union13"),
    union7: makeNodeComponent("union7"),
    union14: makeNodeComponent("union14"),
    rectangle21: makeNodeComponent("rectangle21"),
    group20: makeNodeComponent("group20"),
    rectangle18: makeNodeComponent("rectangle18"),
    // Metadata about props expected for PlasmicAboutPage
    internalVariantProps: PlasmicAboutPage__VariantProps,
    internalArgProps: PlasmicAboutPage__ArgProps
  }
);

export default PlasmicAboutPage;
/* prettier-ignore-end */
