// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iw4cFYZtgxW7YvDehgMC47
// Component: 3q349IpaNzw
import * as React from "react";
import Head from "next/head";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_project_web.module.css"; // plasmic-import: iw4cFYZtgxW7YvDehgMC47/projectcss
import * as sty from "./PlasmicNewPage.module.css"; // plasmic-import: 3q349IpaNzw/css
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: RWzvUW32AX/icon
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: 4NZJoj-fIt/icon
import Line9Icon from "./icons/PlasmicIcon__Line9"; // plasmic-import: QdSNciHXdvM/icon
import Line4Icon from "./icons/PlasmicIcon__Line4"; // plasmic-import: vY-U8OLG9IH/icon
import Line6Icon from "./icons/PlasmicIcon__Line6"; // plasmic-import: RQYW1BLdalZ/icon
import Line8Icon from "./icons/PlasmicIcon__Line8"; // plasmic-import: OWLbkpHPcZo/icon
import Polygon1Icon from "./icons/PlasmicIcon__Polygon1"; // plasmic-import: QaRBHQulwLs/icon
import Rectangle20Icon from "./icons/PlasmicIcon__Rectangle20"; // plasmic-import: zWq4rB1ZbJo/icon
import Line13Icon from "./icons/PlasmicIcon__Line13"; // plasmic-import: rZUomkuHyn0/icon
import Arrow2Icon from "./icons/PlasmicIcon__Arrow2"; // plasmic-import: d9dK44K72X2/icon
import Line14Icon from "./icons/PlasmicIcon__Line14"; // plasmic-import: jPhu6UZ0A6X/icon

export const PlasmicNewPage__VariantProps = new Array();

export const PlasmicNewPage__ArgProps = new Array();

function PlasmicNewPage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"newsPageDesktop"}
            data-plasmic-override={overrides.newsPageDesktop}
            className={classNames(defaultcss.all, sty.newsPageDesktop)}
          >
            {false ? (
              <Line5Icon
                className={classNames(defaultcss.all, sty.svg__tUeyd)}
                role={"img"}
              />
            ) : null}

            <div
              data-plasmic-name={"photo202108171656131"}
              data-plasmic-override={overrides.photo202108171656131}
              className={classNames(defaultcss.all, sty.photo202108171656131)}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__xiXQi)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__bNpcw)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__q7Vy1)}
              role={"img"}
            />

            <Line9Icon
              className={classNames(defaultcss.all, sty.svg__iaCp4)}
              role={"img"}
            />

            <Line9Icon
              className={classNames(defaultcss.all, sty.svg__nPunc)}
              role={"img"}
            />

            <Line4Icon
              className={classNames(defaultcss.all, sty.svg__u1)}
              role={"img"}
            />

            <Line6Icon
              className={classNames(defaultcss.all, sty.svg__gKlLg)}
              role={"img"}
            />

            <Line8Icon
              className={classNames(defaultcss.all, sty.svg___8FxWs)}
              role={"img"}
            />

            <div
              data-plasmic-name={"group8"}
              data-plasmic-override={overrides.group8}
              className={classNames(defaultcss.all, sty.group8)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__nK0Ox
                )}
              >
                {"О ПРОЕКТЕ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___2LkMl
                )}
              >
                {"ПОДДЕРЖАТЬ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__i5B7Q
                )}
              >
                {"ЛЮДИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__vGsSr
                )}
              >
                {"НОВОСТИ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__gVjll
                )}
              >
                {"КАРТА ПРЕСТУПНИКОВ"}
              </div>
            </div>

            <div
              data-plasmic-name={"group1"}
              data-plasmic-override={overrides.group1}
              className={classNames(defaultcss.all, sty.group1)}
            >
              <div
                data-plasmic-name={"verify1"}
                data-plasmic-override={overrides.verify1}
                className={classNames(defaultcss.all, sty.verify1)}
              />

              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(defaultcss.all, sty.rectangle3)}
              />
            </div>

            <div
              data-plasmic-name={"rectangle24"}
              data-plasmic-override={overrides.rectangle24}
              className={classNames(defaultcss.all, sty.rectangle24)}
            />

            <div
              data-plasmic-name={"group10"}
              data-plasmic-override={overrides.group10}
              className={classNames(defaultcss.all, sty.group10)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__ybaIr
                )}
              >
                {"Выбрать регион"}
              </div>

              <Polygon1Icon
                className={classNames(defaultcss.all, sty.svg__lWNnF)}
                role={"img"}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__kkBiu
              )}
            >
              {"ВСЕ НОВОСТИ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__phKXo
              )}
            >
              {"НАШИ ПАРТНЕРЫ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__xmHqp
              )}
            >
              {"ИХ ЧАСТО ИЩУТ"}
            </div>

            <div
              data-plasmic-name={"profile"}
              data-plasmic-override={overrides.profile}
              className={classNames(defaultcss.all, sty.profile)}
            >
              <div
                data-plasmic-name={"group24"}
                data-plasmic-override={overrides.group24}
                className={classNames(defaultcss.all, sty.group24)}
              >
                <div
                  data-plasmic-name={"image27"}
                  data-plasmic-override={overrides.image27}
                  className={classNames(defaultcss.all, sty.image27)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__owfn)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__s40Rs
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__miF3
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile2"}
              data-plasmic-override={overrides.profile2}
              className={classNames(defaultcss.all, sty.profile2)}
            >
              <div
                data-plasmic-name={"group25"}
                data-plasmic-override={overrides.group25}
                className={classNames(defaultcss.all, sty.group25)}
              >
                <div
                  data-plasmic-name={"image28"}
                  data-plasmic-override={overrides.image28}
                  className={classNames(defaultcss.all, sty.image28)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__tlflf)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__rryEd
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__kl4Oj
                )}
              >
                {"Терехов Александр Александрович"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile3"}
              data-plasmic-override={overrides.profile3}
              className={classNames(defaultcss.all, sty.profile3)}
            >
              <div
                data-plasmic-name={"group23"}
                data-plasmic-override={overrides.group23}
                className={classNames(defaultcss.all, sty.group23)}
              >
                <div
                  data-plasmic-name={"image26"}
                  data-plasmic-override={overrides.image26}
                  className={classNames(defaultcss.all, sty.image26)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg___1OxHg)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__sYblx
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__napG
                )}
              >
                {"Занько Дмитрий Александрович"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile4"}
              data-plasmic-override={overrides.profile4}
              className={classNames(defaultcss.all, sty.profile4)}
            >
              <div
                data-plasmic-name={"group26"}
                data-plasmic-override={overrides.group26}
                className={classNames(defaultcss.all, sty.group26)}
              >
                <div
                  data-plasmic-name={"image29"}
                  data-plasmic-override={overrides.image29}
                  className={classNames(defaultcss.all, sty.image29)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__dzeeF)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__cDkr
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__kbfZj
                )}
              >
                {"Бородич Лина Ивановна"}
              </div>
            </div>

            <div
              data-plasmic-name={"profile5"}
              data-plasmic-override={overrides.profile5}
              className={classNames(defaultcss.all, sty.profile5)}
            >
              <div
                data-plasmic-name={"group27"}
                data-plasmic-override={overrides.group27}
                className={classNames(defaultcss.all, sty.group27)}
              >
                <div
                  data-plasmic-name={"image30"}
                  data-plasmic-override={overrides.image30}
                  className={classNames(defaultcss.all, sty.image30)}
                />
              </div>

              <Rectangle20Icon
                className={classNames(defaultcss.all, sty.svg__sl5DE)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__pfyxw
                )}
              >
                {"Милиционер"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__e1ALk
                )}
              >
                {"Терехов Александр Александрович"}
              </div>
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__pbygE
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/ видео подтверждения и тра-тра-та наш бот @botbotbot"
              }
            </div>

            <div
              data-plasmic-name={"union1"}
              data-plasmic-override={overrides.union1}
              className={classNames(defaultcss.all, sty.union1)}
            />

            <div
              data-plasmic-name={"union8"}
              data-plasmic-override={overrides.union8}
              className={classNames(defaultcss.all, sty.union8)}
            />

            <div
              data-plasmic-name={"union3"}
              data-plasmic-override={overrides.union3}
              className={classNames(defaultcss.all, sty.union3)}
            />

            <div
              data-plasmic-name={"union9"}
              data-plasmic-override={overrides.union9}
              className={classNames(defaultcss.all, sty.union9)}
            />

            <div
              data-plasmic-name={"union5"}
              data-plasmic-override={overrides.union5}
              className={classNames(defaultcss.all, sty.union5)}
            />

            <div
              data-plasmic-name={"union10"}
              data-plasmic-override={overrides.union10}
              className={classNames(defaultcss.all, sty.union10)}
            />

            <div
              data-plasmic-name={"union2"}
              data-plasmic-override={overrides.union2}
              className={classNames(defaultcss.all, sty.union2)}
            />

            <div
              data-plasmic-name={"union11"}
              data-plasmic-override={overrides.union11}
              className={classNames(defaultcss.all, sty.union11)}
            />

            <div
              data-plasmic-name={"union4"}
              data-plasmic-override={overrides.union4}
              className={classNames(defaultcss.all, sty.union4)}
            />

            <div
              data-plasmic-name={"union12"}
              data-plasmic-override={overrides.union12}
              className={classNames(defaultcss.all, sty.union12)}
            />

            <div
              data-plasmic-name={"union6"}
              data-plasmic-override={overrides.union6}
              className={classNames(defaultcss.all, sty.union6)}
            />

            <div
              data-plasmic-name={"union13"}
              data-plasmic-override={overrides.union13}
              className={classNames(defaultcss.all, sty.union13)}
            />

            <div
              data-plasmic-name={"union7"}
              data-plasmic-override={overrides.union7}
              className={classNames(defaultcss.all, sty.union7)}
            />

            <div
              data-plasmic-name={"union14"}
              data-plasmic-override={overrides.union14}
              className={classNames(defaultcss.all, sty.union14)}
            />

            <div
              data-plasmic-name={"rectangle21"}
              data-plasmic-override={overrides.rectangle21}
              className={classNames(defaultcss.all, sty.rectangle21)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__dvMLp
              )}
            >
              {
                "Публикуемые личные данные получены из открытых источников методом социальной инженерии или же непосредственно от читателей. Данные публикуются исключительно с целью упрощения последующего расследования преступлений. \n\nКоманда чкб не призывает к насилию. выступает против любого вида дискриминации и порицает разжигание социальной вражды."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__gwztj
              )}
            >
              {"Связаться с нами через бота"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__nrrcr
              )}
            >
              {"Ошибка в тексте?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__gcfvn
              )}
            >
              {"ЧЕРНАЯ КНИГА БЕЛАРУСИ"}
            </div>

            <div
              data-plasmic-name={"group20"}
              data-plasmic-override={overrides.group20}
              className={classNames(defaultcss.all, sty.group20)}
            >
              <div
                data-plasmic-name={"rectangle18"}
                data-plasmic-override={overrides.rectangle18}
                className={classNames(defaultcss.all, sty.rectangle18)}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__jdG4O
              )}
            >
              {
                "Все, кто попадают в Чёрную книгу — это те, на кого есть документальные/ фото/"
              }
            </div>

            <div
              data-plasmic-name={"group28"}
              data-plasmic-override={overrides.group28}
              className={classNames(defaultcss.all, sty.group28)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__iQrev
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__x9Ip5
                )}
              >
                {
                  "Суд города Барановичи вынес решение по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением..."
                }
              </div>

              <div
                data-plasmic-name={"group29"}
                data-plasmic-override={overrides.group29}
                className={classNames(defaultcss.all, sty.group29)}
              >
                <div
                  data-plasmic-name={"image31"}
                  data-plasmic-override={overrides.image31}
                  className={classNames(defaultcss.all, sty.image31)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"group30"}
              data-plasmic-override={overrides.group30}
              className={classNames(defaultcss.all, sty.group30)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__reqKu
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__doas
                )}
              >
                {
                  "Суд города Барановичи вынес решение по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением..."
                }
              </div>

              <div
                data-plasmic-name={"group31"}
                data-plasmic-override={overrides.group31}
                className={classNames(defaultcss.all, sty.group31)}
              >
                <div
                  data-plasmic-name={"image32"}
                  data-plasmic-override={overrides.image32}
                  className={classNames(defaultcss.all, sty.image32)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"group32"}
              data-plasmic-override={overrides.group32}
              className={classNames(defaultcss.all, sty.group32)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__cxtO3
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__ufUb4
                )}
              >
                {
                  "Суд города Барановичи вынес решение по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением..."
                }
              </div>

              <div
                data-plasmic-name={"group33"}
                data-plasmic-override={overrides.group33}
                className={classNames(defaultcss.all, sty.group33)}
              >
                <div
                  data-plasmic-name={"image33"}
                  data-plasmic-override={overrides.image33}
                  className={classNames(defaultcss.all, sty.image33)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"group34"}
              data-plasmic-override={overrides.group34}
              className={classNames(defaultcss.all, sty.group34)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___9JJy1
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__kzufS
                )}
              >
                {
                  'Суд города Барановичи вынес решение (https://t.me/viasna96/6750) по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением Караева (https://t.me/BlackBookBelarus/2032) он написал комментарий “ч*рка гребаный”. Этим он "публично оскорбил представителя власти в связи с выполнением им служебных обязанностей"...'
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__dhQ3Z
                )}
              >
                {"21.08.2021"}
              </div>

              <div
                data-plasmic-name={"group35"}
                data-plasmic-override={overrides.group35}
                className={classNames(defaultcss.all, sty.group35)}
              >
                <div
                  data-plasmic-name={"image34"}
                  data-plasmic-override={overrides.image34}
                  className={classNames(defaultcss.all, sty.image34)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"group36"}
              data-plasmic-override={overrides.group36}
              className={classNames(defaultcss.all, sty.group36)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__vjq0N
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__nYGq
                )}
              >
                {
                  "Суд города Барановичи вынес решение (https://t.me/viasna96/6750) по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением Караева"
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__i7Cf
                )}
              >
                {"21.08.2021"}
              </div>

              <div
                data-plasmic-name={"group37"}
                data-plasmic-override={overrides.group37}
                className={classNames(defaultcss.all, sty.group37)}
              >
                <div
                  data-plasmic-name={"image35"}
                  data-plasmic-override={overrides.image35}
                  className={classNames(defaultcss.all, sty.image35)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"group38"}
              data-plasmic-override={overrides.group38}
              className={classNames(defaultcss.all, sty.group38)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__lex1T
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___4Zs1S
                )}
              >
                {
                  'Суд города Барановичи вынес решение (https://t.me/viasna96/6750) по делу Дениса Денисова. Мужчину обвинили в том, что в чате «Барановичи свободные» под видео с выступлением Караева (https://t.me/BlackBookBelarus/2032) он написал комментарий “ч*рка гребаный”. Этим он "публично оскорбил представителя власти в связи с выполнением им служебных обязанностей"...'
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__wRiEi
                )}
              >
                {"21.08.2021"}
              </div>

              <div
                data-plasmic-name={"group39"}
                data-plasmic-override={overrides.group39}
                className={classNames(defaultcss.all, sty.group39)}
              >
                <div
                  data-plasmic-name={"image36"}
                  data-plasmic-override={overrides.image36}
                  className={classNames(defaultcss.all, sty.image36)}
                />
              </div>
            </div>

            <Line13Icon
              className={classNames(defaultcss.all, sty.svg__feWu)}
              role={"img"}
            />

            <div
              data-plasmic-name={"group40"}
              data-plasmic-override={overrides.group40}
              className={classNames(defaultcss.all, sty.group40)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___6RgTt
                )}
              >
                {"Загрузить больше"}
              </div>

              <Arrow2Icon
                className={classNames(defaultcss.all, sty.svg__amSuh)}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"group41"}
              data-plasmic-override={overrides.group41}
              className={classNames(defaultcss.all, sty.group41)}
            >
              <div
                data-plasmic-name={"group42"}
                data-plasmic-override={overrides.group42}
                className={classNames(defaultcss.all, sty.group42)}
              >
                <div
                  data-plasmic-name={"image37"}
                  data-plasmic-override={overrides.image37}
                  className={classNames(defaultcss.all, sty.image37)}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___54Ar0
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__uOohj
                )}
              >
                {"21.08.2021"}
              </div>
            </div>

            <div
              data-plasmic-name={"group43"}
              data-plasmic-override={overrides.group43}
              className={classNames(defaultcss.all, sty.group43)}
            >
              <div
                data-plasmic-name={"group44"}
                data-plasmic-override={overrides.group44}
                className={classNames(defaultcss.all, sty.group44)}
              >
                <div
                  data-plasmic-name={"image38"}
                  data-plasmic-override={overrides.image38}
                  className={classNames(defaultcss.all, sty.image38)}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__eyVJy
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__i7Omj
                )}
              >
                {"21.08.2021"}
              </div>
            </div>

            <div
              data-plasmic-name={"group45"}
              data-plasmic-override={overrides.group45}
              className={classNames(defaultcss.all, sty.group45)}
            >
              <div
                data-plasmic-name={"group46"}
                data-plasmic-override={overrides.group46}
                className={classNames(defaultcss.all, sty.group46)}
              >
                <div
                  data-plasmic-name={"image39"}
                  data-plasmic-override={overrides.image39}
                  className={classNames(defaultcss.all, sty.image39)}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__yNmF3
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__pqnDw
                )}
              >
                {"21.08.2021"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__aYUk
                )}
              >
                {
                  "Суд города Барановичи вынес решение (https://t.me/viasna96/6750) по делу Дениса Денисова. Мужчину обвинили в том, что... "
                }
              </div>
            </div>

            <div
              data-plasmic-name={"group47"}
              data-plasmic-override={overrides.group47}
              className={classNames(defaultcss.all, sty.group47)}
            >
              <div
                data-plasmic-name={"group48"}
                data-plasmic-override={overrides.group48}
                className={classNames(defaultcss.all, sty.group48)}
              >
                <div
                  data-plasmic-name={"image40"}
                  data-plasmic-override={overrides.image40}
                  className={classNames(defaultcss.all, sty.image40)}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__rtbtg
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__ov6Yj
                )}
              >
                {"21.08.2021"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__gfPok
                )}
              >
                {
                  "Суд города Барановичи вынес решение (https://t.me/viasna96/6750) по делу Дениса Денисова. Мужчину обвинили в том, что... "
                }
              </div>
            </div>

            <div
              data-plasmic-name={"group49"}
              data-plasmic-override={overrides.group49}
              className={classNames(defaultcss.all, sty.group49)}
            >
              <div
                data-plasmic-name={"group50"}
                data-plasmic-override={overrides.group50}
                className={classNames(defaultcss.all, sty.group50)}
              >
                <div
                  data-plasmic-name={"image41"}
                  data-plasmic-override={overrides.image41}
                  className={classNames(defaultcss.all, sty.image41)}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__bv1Sg
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__ir3X6
                )}
              >
                {"21.08.2021"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__mw3Yi
                )}
              >
                {
                  "Суд города Барановичи вынес решение (https://t.me/viasna96/6750) по делу Дениса Денисова. Мужчину обвинили в том, что... "
                }
              </div>
            </div>

            <div
              data-plasmic-name={"group51"}
              data-plasmic-override={overrides.group51}
              className={classNames(defaultcss.all, sty.group51)}
            >
              <div
                data-plasmic-name={"group52"}
                data-plasmic-override={overrides.group52}
                className={classNames(defaultcss.all, sty.group52)}
              >
                <div
                  data-plasmic-name={"image42"}
                  data-plasmic-override={overrides.image42}
                  className={classNames(defaultcss.all, sty.image42)}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__u4I0I
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__afX2E
                )}
              >
                {"21.08.2021"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__yz9Hp
                )}
              >
                {
                  "Суд города Барановичи вынес решение (https://t.me/viasna96/6750) по делу Дениса Денисова. Мужчину обвинили в том, что... "
                }
              </div>
            </div>

            <div
              data-plasmic-name={"group53"}
              data-plasmic-override={overrides.group53}
              className={classNames(defaultcss.all, sty.group53)}
            >
              <div
                data-plasmic-name={"group54"}
                data-plasmic-override={overrides.group54}
                className={classNames(defaultcss.all, sty.group54)}
              >
                <div
                  data-plasmic-name={"image43"}
                  data-plasmic-override={overrides.image43}
                  className={classNames(defaultcss.all, sty.image43)}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__kmhMv
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__wayNi
                )}
              >
                {"21.08.2021"}
              </div>
            </div>

            <div
              data-plasmic-name={"group55"}
              data-plasmic-override={overrides.group55}
              className={classNames(defaultcss.all, sty.group55)}
            >
              <div
                data-plasmic-name={"group56"}
                data-plasmic-override={overrides.group56}
                className={classNames(defaultcss.all, sty.group56)}
              >
                <div
                  data-plasmic-name={"image44"}
                  data-plasmic-override={overrides.image44}
                  className={classNames(defaultcss.all, sty.image44)}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__hZdNt
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__qBzfv
                )}
              >
                {"21.08.2021"}
              </div>
            </div>

            <div
              data-plasmic-name={"group57"}
              data-plasmic-override={overrides.group57}
              className={classNames(defaultcss.all, sty.group57)}
            >
              <div
                data-plasmic-name={"group58"}
                data-plasmic-override={overrides.group58}
                className={classNames(defaultcss.all, sty.group58)}
              >
                <div
                  data-plasmic-name={"image45"}
                  data-plasmic-override={overrides.image45}
                  className={classNames(defaultcss.all, sty.image45)}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__tNoUa
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__nAai
                )}
              >
                {"21.08.2021"}
              </div>
            </div>

            <div
              data-plasmic-name={"group59"}
              data-plasmic-override={overrides.group59}
              className={classNames(defaultcss.all, sty.group59)}
            >
              <div
                data-plasmic-name={"group60"}
                data-plasmic-override={overrides.group60}
                className={classNames(defaultcss.all, sty.group60)}
              >
                <div
                  data-plasmic-name={"image46"}
                  data-plasmic-override={overrides.image46}
                  className={classNames(defaultcss.all, sty.image46)}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__uAxDp
                )}
              >
                {"Два года за то, что назвал Караева «Ч*рка гребаный»"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__pv9TK
                )}
              >
                {"21.08.2021"}
              </div>
            </div>

            <Line14Icon
              className={classNames(defaultcss.all, sty.svg___6TVsl)}
              role={"img"}
            />

            <Line14Icon
              className={classNames(defaultcss.all, sty.svg__xZgbz)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(defaultcss.all, sty.svg__mMsFy)}
              role={"img"}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "newsPageDesktop",
    "photo202108171656131",
    "group8",
    "group1",
    "verify1",
    "rectangle3",
    "rectangle24",
    "group10",
    "profile",
    "group24",
    "image27",
    "profile2",
    "group25",
    "image28",
    "profile3",
    "group23",
    "image26",
    "profile4",
    "group26",
    "image29",
    "profile5",
    "group27",
    "image30",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18",
    "group28",
    "group29",
    "image31",
    "group30",
    "group31",
    "image32",
    "group32",
    "group33",
    "image33",
    "group34",
    "group35",
    "image34",
    "group36",
    "group37",
    "image35",
    "group38",
    "group39",
    "image36",
    "group40",
    "group41",
    "group42",
    "image37",
    "group43",
    "group44",
    "image38",
    "group45",
    "group46",
    "image39",
    "group47",
    "group48",
    "image40",
    "group49",
    "group50",
    "image41",
    "group51",
    "group52",
    "image42",
    "group53",
    "group54",
    "image43",
    "group55",
    "group56",
    "image44",
    "group57",
    "group58",
    "image45",
    "group59",
    "group60",
    "image46"
  ],

  newsPageDesktop: [
    "newsPageDesktop",
    "photo202108171656131",
    "group8",
    "group1",
    "verify1",
    "rectangle3",
    "rectangle24",
    "group10",
    "profile",
    "group24",
    "image27",
    "profile2",
    "group25",
    "image28",
    "profile3",
    "group23",
    "image26",
    "profile4",
    "group26",
    "image29",
    "profile5",
    "group27",
    "image30",
    "union1",
    "union8",
    "union3",
    "union9",
    "union5",
    "union10",
    "union2",
    "union11",
    "union4",
    "union12",
    "union6",
    "union13",
    "union7",
    "union14",
    "rectangle21",
    "group20",
    "rectangle18",
    "group28",
    "group29",
    "image31",
    "group30",
    "group31",
    "image32",
    "group32",
    "group33",
    "image33",
    "group34",
    "group35",
    "image34",
    "group36",
    "group37",
    "image35",
    "group38",
    "group39",
    "image36",
    "group40",
    "group41",
    "group42",
    "image37",
    "group43",
    "group44",
    "image38",
    "group45",
    "group46",
    "image39",
    "group47",
    "group48",
    "image40",
    "group49",
    "group50",
    "image41",
    "group51",
    "group52",
    "image42",
    "group53",
    "group54",
    "image43",
    "group55",
    "group56",
    "image44",
    "group57",
    "group58",
    "image45",
    "group59",
    "group60",
    "image46"
  ],

  photo202108171656131: ["photo202108171656131"],
  group8: ["group8"],
  group1: ["group1", "verify1", "rectangle3"],
  verify1: ["verify1"],
  rectangle3: ["rectangle3"],
  rectangle24: ["rectangle24"],
  group10: ["group10"],
  profile: ["profile", "group24", "image27"],
  group24: ["group24", "image27"],
  image27: ["image27"],
  profile2: ["profile2", "group25", "image28"],
  group25: ["group25", "image28"],
  image28: ["image28"],
  profile3: ["profile3", "group23", "image26"],
  group23: ["group23", "image26"],
  image26: ["image26"],
  profile4: ["profile4", "group26", "image29"],
  group26: ["group26", "image29"],
  image29: ["image29"],
  profile5: ["profile5", "group27", "image30"],
  group27: ["group27", "image30"],
  image30: ["image30"],
  union1: ["union1"],
  union8: ["union8"],
  union3: ["union3"],
  union9: ["union9"],
  union5: ["union5"],
  union10: ["union10"],
  union2: ["union2"],
  union11: ["union11"],
  union4: ["union4"],
  union12: ["union12"],
  union6: ["union6"],
  union13: ["union13"],
  union7: ["union7"],
  union14: ["union14"],
  rectangle21: ["rectangle21"],
  group20: ["group20", "rectangle18"],
  rectangle18: ["rectangle18"],
  group28: ["group28", "group29", "image31"],
  group29: ["group29", "image31"],
  image31: ["image31"],
  group30: ["group30", "group31", "image32"],
  group31: ["group31", "image32"],
  image32: ["image32"],
  group32: ["group32", "group33", "image33"],
  group33: ["group33", "image33"],
  image33: ["image33"],
  group34: ["group34", "group35", "image34"],
  group35: ["group35", "image34"],
  image34: ["image34"],
  group36: ["group36", "group37", "image35"],
  group37: ["group37", "image35"],
  image35: ["image35"],
  group38: ["group38", "group39", "image36"],
  group39: ["group39", "image36"],
  image36: ["image36"],
  group40: ["group40"],
  group41: ["group41", "group42", "image37"],
  group42: ["group42", "image37"],
  image37: ["image37"],
  group43: ["group43", "group44", "image38"],
  group44: ["group44", "image38"],
  image38: ["image38"],
  group45: ["group45", "group46", "image39"],
  group46: ["group46", "image39"],
  image39: ["image39"],
  group47: ["group47", "group48", "image40"],
  group48: ["group48", "image40"],
  image40: ["image40"],
  group49: ["group49", "group50", "image41"],
  group50: ["group50", "image41"],
  image41: ["image41"],
  group51: ["group51", "group52", "image42"],
  group52: ["group52", "image42"],
  image42: ["image42"],
  group53: ["group53", "group54", "image43"],
  group54: ["group54", "image43"],
  image43: ["image43"],
  group55: ["group55", "group56", "image44"],
  group56: ["group56", "image44"],
  image44: ["image44"],
  group57: ["group57", "group58", "image45"],
  group58: ["group58", "image45"],
  image45: ["image45"],
  group59: ["group59", "group60", "image46"],
  group60: ["group60", "image46"],
  image46: ["image46"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNewPage__ArgProps,
      internalVariantPropNames: PlasmicNewPage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicNewPage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewPage";
  } else {
    func.displayName = `PlasmicNewPage.${nodeName}`;
  }
  return func;
}

export const PlasmicNewPage = Object.assign(
  // Top-level PlasmicNewPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    newsPageDesktop: makeNodeComponent("newsPageDesktop"),
    photo202108171656131: makeNodeComponent("photo202108171656131"),
    group8: makeNodeComponent("group8"),
    group1: makeNodeComponent("group1"),
    verify1: makeNodeComponent("verify1"),
    rectangle3: makeNodeComponent("rectangle3"),
    rectangle24: makeNodeComponent("rectangle24"),
    group10: makeNodeComponent("group10"),
    profile: makeNodeComponent("profile"),
    group24: makeNodeComponent("group24"),
    image27: makeNodeComponent("image27"),
    profile2: makeNodeComponent("profile2"),
    group25: makeNodeComponent("group25"),
    image28: makeNodeComponent("image28"),
    profile3: makeNodeComponent("profile3"),
    group23: makeNodeComponent("group23"),
    image26: makeNodeComponent("image26"),
    profile4: makeNodeComponent("profile4"),
    group26: makeNodeComponent("group26"),
    image29: makeNodeComponent("image29"),
    profile5: makeNodeComponent("profile5"),
    group27: makeNodeComponent("group27"),
    image30: makeNodeComponent("image30"),
    union1: makeNodeComponent("union1"),
    union8: makeNodeComponent("union8"),
    union3: makeNodeComponent("union3"),
    union9: makeNodeComponent("union9"),
    union5: makeNodeComponent("union5"),
    union10: makeNodeComponent("union10"),
    union2: makeNodeComponent("union2"),
    union11: makeNodeComponent("union11"),
    union4: makeNodeComponent("union4"),
    union12: makeNodeComponent("union12"),
    union6: makeNodeComponent("union6"),
    union13: makeNodeComponent("union13"),
    union7: makeNodeComponent("union7"),
    union14: makeNodeComponent("union14"),
    rectangle21: makeNodeComponent("rectangle21"),
    group20: makeNodeComponent("group20"),
    rectangle18: makeNodeComponent("rectangle18"),
    group28: makeNodeComponent("group28"),
    group29: makeNodeComponent("group29"),
    image31: makeNodeComponent("image31"),
    group30: makeNodeComponent("group30"),
    group31: makeNodeComponent("group31"),
    image32: makeNodeComponent("image32"),
    group32: makeNodeComponent("group32"),
    group33: makeNodeComponent("group33"),
    image33: makeNodeComponent("image33"),
    group34: makeNodeComponent("group34"),
    group35: makeNodeComponent("group35"),
    image34: makeNodeComponent("image34"),
    group36: makeNodeComponent("group36"),
    group37: makeNodeComponent("group37"),
    image35: makeNodeComponent("image35"),
    group38: makeNodeComponent("group38"),
    group39: makeNodeComponent("group39"),
    image36: makeNodeComponent("image36"),
    group40: makeNodeComponent("group40"),
    group41: makeNodeComponent("group41"),
    group42: makeNodeComponent("group42"),
    image37: makeNodeComponent("image37"),
    group43: makeNodeComponent("group43"),
    group44: makeNodeComponent("group44"),
    image38: makeNodeComponent("image38"),
    group45: makeNodeComponent("group45"),
    group46: makeNodeComponent("group46"),
    image39: makeNodeComponent("image39"),
    group47: makeNodeComponent("group47"),
    group48: makeNodeComponent("group48"),
    image40: makeNodeComponent("image40"),
    group49: makeNodeComponent("group49"),
    group50: makeNodeComponent("group50"),
    image41: makeNodeComponent("image41"),
    group51: makeNodeComponent("group51"),
    group52: makeNodeComponent("group52"),
    image42: makeNodeComponent("image42"),
    group53: makeNodeComponent("group53"),
    group54: makeNodeComponent("group54"),
    image43: makeNodeComponent("image43"),
    group55: makeNodeComponent("group55"),
    group56: makeNodeComponent("group56"),
    image44: makeNodeComponent("image44"),
    group57: makeNodeComponent("group57"),
    group58: makeNodeComponent("group58"),
    image45: makeNodeComponent("image45"),
    group59: makeNodeComponent("group59"),
    group60: makeNodeComponent("group60"),
    image46: makeNodeComponent("image46"),
    // Metadata about props expected for PlasmicNewPage
    internalVariantProps: PlasmicNewPage__VariantProps,
    internalArgProps: PlasmicNewPage__ArgProps
  }
);

export default PlasmicNewPage;
/* prettier-ignore-end */
